package cv;
/**
 * <i>native declaration : cv\include\cvtypes.h:92</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.free.fr/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a>, <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class CvChainPtReader extends com.ochafik.lang.jnaerator.runtime.Structure {
	public CvChainPtReader() {
		super();
	}
	public ByReference byReference() { return setupClone(new ByReference()); }
	public ByValue byValue() { return setupClone(new ByValue()); }
	public CvChainPtReader clone() { return setupClone(new CvChainPtReader()); }
	public static class ByReference extends CvChainPtReader implements com.sun.jna.Structure.ByReference {}
	public static class ByValue extends CvChainPtReader implements com.sun.jna.Structure.ByValue {}
}
