package cv;
/**
 * <i>native declaration : cv\include\cv.h:1355</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.free.fr/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a>, <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class CvStereoBMState extends com.ochafik.lang.jnaerator.runtime.Structure {
	/**
	 * pre-filtering (normalization of input images)<br>
	 * =CV_STEREO_BM_NORMALIZED_RESPONSE now
	 */
	public int preFilterType;
	/// averaging window size: ~5x5..21x21
	public int preFilterSize;
	/// the output of pre-filtering is clipped by [-preFilterCap,preFilterCap]
	public int preFilterCap;
	/**
	 * correspondence using Sum of Absolute Difference (SAD)<br>
	 * ~5x5..21x21
	 */
	public int SADWindowSize;
	/// minimum disparity (can be negative)
	public int minDisparity;
	/// maximum disparity - minimum disparity (> 0)
	public int numberOfDisparities;
	/**
	 * post-filtering<br>
	 * the disparity is only computed for pixels
	 */
	public int textureThreshold;
	/**
	 * with textured enough neighborhood<br>
	 * accept the computed disparity d* only if
	 */
	public int uniquenessRatio;
	/**
	 * for any d != d*+/-1 within the search range.<br>
	 * disparity variation window
	 */
	public int speckleWindowSize;
	/// acceptable range of variation in window
	public int speckleRange;
	/// temporary buffers
	public cxcore.CvMat.ByReference preFilteredImg0;
	public cxcore.CvMat.ByReference preFilteredImg1;
	public cxcore.CvMat.ByReference slidingSumBuf;
	public CvStereoBMState() {
		super();
	}
	public ByReference byReference() { return setupClone(new ByReference()); }
	public ByValue byValue() { return setupClone(new ByValue()); }
	public CvStereoBMState clone() { return setupClone(new CvStereoBMState()); }
	public static class ByReference extends CvStereoBMState implements com.sun.jna.Structure.ByReference {}
	public static class ByValue extends CvStereoBMState implements com.sun.jna.Structure.ByValue {}
}
