package cv;
/**
 * <i>native declaration : cv\include\cv.h:1398</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.free.fr/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a>, <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class CvStereoGCState extends com.ochafik.lang.jnaerator.runtime.Structure {
	public int Ithreshold;
	public int interactionRadius;
	public float K;
	public float lambda;
	public float lambda1;
	public float lambda2;
	public int occlusionCost;
	public int minDisparity;
	public int numberOfDisparities;
	public int maxIters;
	public cxcore.CvMat.ByReference left;
	public cxcore.CvMat.ByReference right;
	public cxcore.CvMat.ByReference dispLeft;
	public cxcore.CvMat.ByReference dispRight;
	public cxcore.CvMat.ByReference ptrLeft;
	public cxcore.CvMat.ByReference ptrRight;
	public cxcore.CvMat.ByReference vtxBuf;
	public cxcore.CvMat.ByReference edgeBuf;
	public CvStereoGCState() {
		super();
	}
	public ByReference byReference() { return setupClone(new ByReference()); }
	public ByValue byValue() { return setupClone(new ByValue()); }
	public CvStereoGCState clone() { return setupClone(new CvStereoGCState()); }
	public static class ByReference extends CvStereoGCState implements com.sun.jna.Structure.ByReference {}
	public static class ByValue extends CvStereoGCState implements com.sun.jna.Structure.ByValue {}
}
