package cv;
/**
 * <i>native declaration : cv\include\cv.h:1080</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.free.fr/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a>, <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class CvSURFParams extends com.ochafik.lang.jnaerator.runtime.Structure {
	public int extended;
	public double hessianThreshold;
	public int nOctaves;
	public int nOctaveLayers;
	public CvSURFParams() {
		super();
	}
	public CvSURFParams(int extended, double hessianThreshold, int nOctaves, int nOctaveLayers) {
		super();
		this.extended = extended;
		this.hessianThreshold = hessianThreshold;
		this.nOctaves = nOctaves;
		this.nOctaveLayers = nOctaveLayers;
	}
	public ByReference byReference() { return setupClone(new ByReference()); }
	public ByValue byValue() { return setupClone(new ByValue()); }
	public CvSURFParams clone() { return setupClone(new CvSURFParams()); }
	public static class ByReference extends CvSURFParams implements com.sun.jna.Structure.ByReference {}
	public static class ByValue extends CvSURFParams implements com.sun.jna.Structure.ByValue {}
}
