package cxcore;
/**
 * <i>native declaration : cxcore\include\cxtypes.h:125</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.free.fr/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a>, <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class Cv32suf extends com.ochafik.lang.jnaerator.runtime.Union {
	public int i;
	public int u;
	public float f;
	public Cv32suf() {
		super();
	}
	public Cv32suf(int i_or_u) {
		super();
		this.u = this.i = i_or_u;
		setType(Integer.TYPE);
	}
	public Cv32suf(float f) {
		super();
		this.f = f;
		setType(Float.TYPE);
	}
	public ByReference byReference() { return setupClone(new ByReference()); }
	public ByValue byValue() { return setupClone(new ByValue()); }
	public Cv32suf clone() { return setupClone(new Cv32suf()); }
	public static class ByReference extends Cv32suf implements com.sun.jna.Structure.ByReference {}
	public static class ByValue extends Cv32suf implements com.sun.jna.Structure.ByValue {}
}
