package cxcore;
/**
 * <i>native declaration : cxcore\include\cxtypes.h:133</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.free.fr/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a>, <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class Cv64suf extends com.ochafik.lang.jnaerator.runtime.Union {
	public long i;
	public long u;
	public double f;
	public Cv64suf() {
		super();
	}
	public Cv64suf(double f) {
		super();
		this.f = f;
		setType(Double.TYPE);
	}
	public Cv64suf(long i_or_u) {
		super();
		this.u = this.i = i_or_u;
		setType(Long.TYPE);
	}
	public ByReference byReference() { return setupClone(new ByReference()); }
	public ByValue byValue() { return setupClone(new ByValue()); }
	public Cv64suf clone() { return setupClone(new Cv64suf()); }
	public static class ByReference extends Cv64suf implements com.sun.jna.Structure.ByReference {}
	public static class ByValue extends Cv64suf implements com.sun.jna.Structure.ByValue {}
}
