package cxcore;
/**
 * <i>native declaration : cxcore\include\cxtypes.h:1591</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.free.fr/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a>, <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class CvAttrList extends com.ochafik.lang.jnaerator.runtime.Structure {
	/// NULL-terminated array of (attribute_name,attribute_value) pairs.
	public com.sun.jna.ptr.PointerByReference attr;
	/// Pointer to next chunk of the attributes list.
	public cxcore.CvAttrList.ByReference next;
	public CvAttrList() {
		super();
	}
	/**
	 * @param attr NULL-terminated array of (attribute_name,attribute_value) pairs.<br>
	 * @param next Pointer to next chunk of the attributes list.
	 */
	public CvAttrList(com.sun.jna.ptr.PointerByReference attr, cxcore.CvAttrList.ByReference next) {
		super();
		this.attr = attr;
		this.next = next;
	}
	public ByReference byReference() { return setupClone(new ByReference()); }
	public ByValue byValue() { return setupClone(new ByValue()); }
	public CvAttrList clone() { return setupClone(new CvAttrList()); }
	public static class ByReference extends CvAttrList implements com.sun.jna.Structure.ByReference {}
	public static class ByValue extends CvAttrList implements com.sun.jna.Structure.ByValue {}
}
