package cxcore;
/**
 * <i>native declaration : cxcore\include\cxtypes.h:1013</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.free.fr/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a>, <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class CvBox2D extends com.ochafik.lang.jnaerator.runtime.Structure {
	/// Center of the box.
	public cxcore.CvPoint2D32f center;
	/// Box width and length.
	public cxcore.CvSize2D32f size;
	/// Angle between the horizontal axis
	public float angle;
	public CvBox2D() {
		super();
	}
	/**
	 * @param center Center of the box.<br>
	 * @param size Box width and length.<br>
	 * @param angle Angle between the horizontal axis
	 */
	public CvBox2D(cxcore.CvPoint2D32f center, cxcore.CvSize2D32f size, float angle) {
		super();
		this.center = center;
		this.size = size;
		this.angle = angle;
	}
	public ByReference byReference() { return setupClone(new ByReference()); }
	public ByValue byValue() { return setupClone(new ByValue()); }
	public CvBox2D clone() { return setupClone(new CvBox2D()); }
	public static class ByReference extends CvBox2D implements com.sun.jna.Structure.ByReference {}
	public static class ByValue extends CvBox2D implements com.sun.jna.Structure.ByValue {}
}
