package cxcore;
/**
 * <i>native declaration : cxcore\include\cxcore.h:1351</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.free.fr/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a>, <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class CvFont extends com.ochafik.lang.jnaerator.runtime.Structure {
	/// =CV_FONT_*
	public int font_face;
	/// font data and metrics
	public com.sun.jna.ptr.IntByReference ascii;
	public com.sun.jna.ptr.IntByReference greek;
	public com.sun.jna.ptr.IntByReference cyrillic;
	public float hscale;
	public float vscale;
	/// slope coefficient: 0 - normal, >0 - italic
	public float shear;
	/// letters thickness
	public int thickness;
	/// horizontal interval between letters
	public float dx;
	public int line_type;
	public CvFont() {
		super();
	}
	public ByReference byReference() { return setupClone(new ByReference()); }
	public ByValue byValue() { return setupClone(new ByValue()); }
	public CvFont clone() { return setupClone(new CvFont()); }
	public static class ByReference extends CvFont implements com.sun.jna.Structure.ByReference {}
	public static class ByValue extends CvFont implements com.sun.jna.Structure.ByValue {}
}
