package cxcore;
/**
 * <i>native declaration : cxcore\include\cxtypes.h:1276</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.free.fr/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a>, <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class CvGraph extends com.ochafik.lang.jnaerator.runtime.Structure {
	public int flags;
	public int header_size;
	public cxcore.CvSeq.ByReference h_prev;
	public cxcore.CvSeq.ByReference h_next;
	public cxcore.CvSeq.ByReference v_prev;
	public cxcore.CvSeq.ByReference v_next;
	public int total;
	public int elem_size;
	public com.sun.jna.ptr.ByteByReference block_max;
	public com.sun.jna.ptr.ByteByReference ptr;
	public int delta_elems;
	public cxcore.CvMemStorage.ByReference storage;
	public cxcore.CvSeqBlock.ByReference free_blocks;
	public cxcore.CvSeqBlock.ByReference first;
	public cxcore.CvSetElem.ByReference free_elems;
	public int active_count;
	public cxcore.CvSet.ByReference edges;
	public CvGraph() {
		super();
	}
	public ByReference byReference() { return setupClone(new ByReference()); }
	public ByValue byValue() { return setupClone(new ByValue()); }
	public CvGraph clone() { return setupClone(new CvGraph()); }
	public static class ByReference extends CvGraph implements com.sun.jna.Structure.ByReference {}
	public static class ByValue extends CvGraph implements com.sun.jna.Structure.ByValue {}
}
