package cxcore;
/**
 * <i>native declaration : cxcore\include\cxtypes.h:1261</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.free.fr/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a>, <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class CvGraphVtx2D extends com.ochafik.lang.jnaerator.runtime.Structure {
	public int flags;
	public cxcore.CvGraphEdge.ByReference first;
	public cxcore.CvPoint2D32f.ByReference ptr;
	public CvGraphVtx2D() {
		super();
	}
	public CvGraphVtx2D(int flags, cxcore.CvGraphEdge.ByReference first, cxcore.CvPoint2D32f.ByReference ptr) {
		super();
		this.flags = flags;
		this.first = first;
		this.ptr = ptr;
	}
	public ByReference byReference() { return setupClone(new ByReference()); }
	public ByValue byValue() { return setupClone(new ByValue()); }
	public CvGraphVtx2D clone() { return setupClone(new CvGraphVtx2D()); }
	public static class ByReference extends CvGraphVtx2D implements com.sun.jna.Structure.ByReference {}
	public static class ByValue extends CvGraphVtx2D implements com.sun.jna.Structure.ByValue {}
}
