package cxcore;
/**
 * <i>native declaration : cxcore\include\cxcore.h:1208</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.free.fr/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a>, <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class CvGraphScanner extends com.ochafik.lang.jnaerator.runtime.Structure {
	/// current graph vertex (or current edge origin)
	public cxcore.CvGraphVtx.ByReference vtx;
	/// current graph edge destination vertex
	public cxcore.CvGraphVtx.ByReference dst;
	/// current edge
	public cxcore.CvGraphEdge.ByReference edge;
	/// the graph
	public cxcore.CvGraph.ByReference graph;
	/// the graph vertex stack
	public cxcore.CvSeq.ByReference stack;
	/// the lower bound of certainly visited vertices
	public int index;
	/// event mask
	public int mask;
	public CvGraphScanner() {
		super();
	}
	/**
	 * @param vtx current graph vertex (or current edge origin)<br>
	 * @param dst current graph edge destination vertex<br>
	 * @param edge current edge<br>
	 * @param graph the graph<br>
	 * @param stack the graph vertex stack<br>
	 * @param index the lower bound of certainly visited vertices<br>
	 * @param mask event mask
	 */
	public CvGraphScanner(cxcore.CvGraphVtx.ByReference vtx, cxcore.CvGraphVtx.ByReference dst, cxcore.CvGraphEdge.ByReference edge, cxcore.CvGraph.ByReference graph, cxcore.CvSeq.ByReference stack, int index, int mask) {
		super();
		this.vtx = vtx;
		this.dst = dst;
		this.edge = edge;
		this.graph = graph;
		this.stack = stack;
		this.index = index;
		this.mask = mask;
	}
	public ByReference byReference() { return setupClone(new ByReference()); }
	public ByValue byValue() { return setupClone(new ByValue()); }
	public CvGraphScanner clone() { return setupClone(new CvGraphScanner()); }
	public static class ByReference extends CvGraphScanner implements com.sun.jna.Structure.ByReference {}
	public static class ByValue extends CvGraphScanner implements com.sun.jna.Structure.ByValue {}
}
