package cxcore;
/**
 * <i>native declaration : cxcore\include\cxtypes.h:761</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.free.fr/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a>, <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class CvHistogram extends com.ochafik.lang.jnaerator.runtime.Structure {
	public int type;
	public highgui.HighguiLibrary.CvArr bins;
	/// For uniform histograms.
	public float[] thresh = new float[32 * 2];
	/// For non-uniform histograms.
	public com.sun.jna.ptr.PointerByReference thresh2;
	/// Embedded matrix header for array histograms.
	public cxcore.CvMatND mat;
	public CvHistogram() {
		super();
	}
	/**
	 * @param thresh For uniform histograms.<br>
	 * @param thresh2 For non-uniform histograms.<br>
	 * @param mat Embedded matrix header for array histograms.
	 */
	public CvHistogram(int type, highgui.HighguiLibrary.CvArr bins, float thresh[], com.sun.jna.ptr.PointerByReference thresh2, cxcore.CvMatND mat) {
		super();
		this.type = type;
		this.bins = bins;
		if (thresh.length != this.thresh.length) 
			throw new java.lang.IllegalArgumentException("Wrong array size !");
		this.thresh = thresh;
		this.thresh2 = thresh2;
		this.mat = mat;
	}
	public ByReference byReference() { return setupClone(new ByReference()); }
	public ByValue byValue() { return setupClone(new ByValue()); }
	public CvHistogram clone() { return setupClone(new CvHistogram()); }
	public static class ByReference extends CvHistogram implements com.sun.jna.Structure.ByReference {}
	public static class ByValue extends CvHistogram implements com.sun.jna.Structure.ByValue {}
}
