package cxcore;
/**
 * <i>native declaration : cxcore\include\cxtypes.h:1103</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.free.fr/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a>, <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class CvMemBlock extends com.ochafik.lang.jnaerator.runtime.Structure {
	public cxcore.CvMemBlock.ByReference prev;
	public cxcore.CvMemBlock.ByReference next;
	public CvMemBlock() {
		super();
	}
	public CvMemBlock(cxcore.CvMemBlock.ByReference prev, cxcore.CvMemBlock.ByReference next) {
		super();
		this.prev = prev;
		this.next = next;
	}
	public ByReference byReference() { return setupClone(new ByReference()); }
	public ByValue byValue() { return setupClone(new ByValue()); }
	public CvMemBlock clone() { return setupClone(new CvMemBlock()); }
	public static class ByReference extends CvMemBlock implements com.sun.jna.Structure.ByReference {}
	public static class ByValue extends CvMemBlock implements com.sun.jna.Structure.ByValue {}
}
