package cxcore;
/**
 * <i>native declaration : cxcore\include\cxtypes.h:1112</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.free.fr/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a>, <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class CvMemStorage extends com.ochafik.lang.jnaerator.runtime.Structure {
	public int signature;
	/// First allocated block.
	public cxcore.CvMemBlock.ByReference bottom;
	/// Current memory block - top of the stack.
	public cxcore.CvMemBlock.ByReference top;
	/// We get new blocks from parent as needed.
	public cxcore.CvMemStorage.ByReference parent;
	/// Block size.
	public int block_size;
	/// Remaining free space in current block.
	public int free_space;
	public CvMemStorage() {
		super();
	}
	/**
	 * @param bottom First allocated block.<br>
	 * @param top Current memory block - top of the stack.<br>
	 * @param parent We get new blocks from parent as needed.<br>
	 * @param block_size Block size.<br>
	 * @param free_space Remaining free space in current block.
	 */
	public CvMemStorage(int signature, cxcore.CvMemBlock.ByReference bottom, cxcore.CvMemBlock.ByReference top, cxcore.CvMemStorage.ByReference parent, int block_size, int free_space) {
		super();
		this.signature = signature;
		this.bottom = bottom;
		this.top = top;
		this.parent = parent;
		this.block_size = block_size;
		this.free_space = free_space;
	}
	public ByReference byReference() { return setupClone(new ByReference()); }
	public ByValue byValue() { return setupClone(new ByValue()); }
	public CvMemStorage clone() { return setupClone(new CvMemStorage()); }
	public static class ByReference extends CvMemStorage implements com.sun.jna.Structure.ByReference {}
	public static class ByValue extends CvMemStorage implements com.sun.jna.Structure.ByValue {}
}
