package cxcore;
/**
 * <i>native declaration : cxcore\include\cxtypes.h:1128</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.free.fr/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a>, <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class CvMemStoragePos extends com.ochafik.lang.jnaerator.runtime.Structure {
	public cxcore.CvMemBlock.ByReference top;
	public int free_space;
	public CvMemStoragePos() {
		super();
	}
	public CvMemStoragePos(cxcore.CvMemBlock.ByReference top, int free_space) {
		super();
		this.top = top;
		this.free_space = free_space;
	}
	public ByReference byReference() { return setupClone(new ByReference()); }
	public ByValue byValue() { return setupClone(new ByValue()); }
	public CvMemStoragePos clone() { return setupClone(new CvMemStoragePos()); }
	public static class ByReference extends CvMemStoragePos implements com.sun.jna.Structure.ByReference {}
	public static class ByValue extends CvMemStoragePos implements com.sun.jna.Structure.ByValue {}
}
