package cxcore;
/**
 * <i>native declaration : cxcore\include\cxtypes.h:1721</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.free.fr/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a>, <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class CvModuleInfo extends com.ochafik.lang.jnaerator.runtime.Structure {
	public cxcore.CvModuleInfo.ByReference next;
	public com.sun.jna.ptr.ByteByReference name;
	public com.sun.jna.ptr.ByteByReference version;
	public cxcore.CvPluginFuncInfo.ByReference func_tab;
	public CvModuleInfo() {
		super();
	}
	public CvModuleInfo(cxcore.CvModuleInfo.ByReference next, com.sun.jna.ptr.ByteByReference name, com.sun.jna.ptr.ByteByReference version, cxcore.CvPluginFuncInfo.ByReference func_tab) {
		super();
		this.next = next;
		this.name = name;
		this.version = version;
		this.func_tab = func_tab;
	}
	public ByReference byReference() { return setupClone(new ByReference()); }
	public ByValue byValue() { return setupClone(new ByValue()); }
	public CvModuleInfo clone() { return setupClone(new CvModuleInfo()); }
	public static class ByReference extends CvModuleInfo implements com.sun.jna.Structure.ByReference {}
	public static class ByValue extends CvModuleInfo implements com.sun.jna.Structure.ByValue {}
}
