package cxcore;
/**
 * <i>native declaration : cxcore\include\cxtypes.h:915</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.free.fr/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a>, <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class CvPoint3D32f extends com.ochafik.lang.jnaerator.runtime.Structure {
	public float x;
	public float y;
	public float z;
	public CvPoint3D32f() {
		super();
	}
	public CvPoint3D32f(float x, float y, float z) {
		super();
		this.x = x;
		this.y = y;
		this.z = z;
	}
	public ByReference byReference() { return setupClone(new ByReference()); }
	public ByValue byValue() { return setupClone(new ByValue()); }
	public CvPoint3D32f clone() { return setupClone(new CvPoint3D32f()); }
	public static class ByReference extends CvPoint3D32f implements com.sun.jna.Structure.ByReference {}
	public static class ByValue extends CvPoint3D32f implements com.sun.jna.Structure.ByValue {}
}
