package cxcore;
/**
 * <i>native declaration : cxcore\include\cxtypes.h:936</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.free.fr/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a>, <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class CvPoint2D64f extends com.ochafik.lang.jnaerator.runtime.Structure {
	public double x;
	public double y;
	public CvPoint2D64f() {
		super();
	}
	public CvPoint2D64f(double x, double y) {
		super();
		this.x = x;
		this.y = y;
	}
	public ByReference byReference() { return setupClone(new ByReference()); }
	public ByValue byValue() { return setupClone(new ByValue()); }
	public CvPoint2D64f clone() { return setupClone(new CvPoint2D64f()); }
	public static class ByReference extends CvPoint2D64f implements com.sun.jna.Structure.ByReference {}
	public static class ByValue extends CvPoint2D64f implements com.sun.jna.Structure.ByValue {}
}
