package cxcore;
/**
 * <i>native declaration : cxcore\include\cxtypes.h:861</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.free.fr/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a>, <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class CvPoint extends com.ochafik.lang.jnaerator.runtime.Structure {
	public int x;
	public int y;
	public CvPoint() {
		super();
	}
	public CvPoint(int x, int y) {
		super();
		this.x = x;
		this.y = y;
	}
	public ByReference byReference() { return setupClone(new ByReference()); }
	public ByValue byValue() { return setupClone(new ByValue()); }
	public CvPoint clone() { return setupClone(new CvPoint()); }
	public static class ByReference extends CvPoint implements com.sun.jna.Structure.ByReference {}
	public static class ByValue extends CvPoint implements com.sun.jna.Structure.ByValue {}
}
