package cxcore;
/**
 * <i>native declaration : cxcore\include\cxtypes.h:791</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.free.fr/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a>, <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class CvRect extends com.ochafik.lang.jnaerator.runtime.Structure {
	public int x;
	public int y;
	public int width;
	public int height;
	public CvRect() {
		super();
	}
	public CvRect(int x, int y, int width, int height) {
		super();
		this.x = x;
		this.y = y;
		this.width = width;
		this.height = height;
	}
	public ByReference byReference() { return setupClone(new ByReference()); }
	public ByValue byValue() { return setupClone(new ByValue()); }
	public CvRect clone() { return setupClone(new CvRect()); }
	public static class ByReference extends CvRect implements com.sun.jna.Structure.ByReference {}
	public static class ByValue extends CvRect implements com.sun.jna.Structure.ByValue {}
}
