package cxcore;
/**
 * <i>native declaration : cxcore\include\cxtypes.h:1063</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.free.fr/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a>, <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class CvScalar extends com.ochafik.lang.jnaerator.runtime.Structure {
	public double[] val = new double[(4)];
	public CvScalar() {
		super();
	}
	public CvScalar(double val[]) {
		super();
		if (val.length != this.val.length) 
			throw new java.lang.IllegalArgumentException("Wrong array size !");
		this.val = val;
	}
	public ByReference byReference() { return setupClone(new ByReference()); }
	public ByValue byValue() { return setupClone(new ByValue()); }
	public CvScalar clone() { return setupClone(new CvScalar()); }
	public static class ByReference extends CvScalar implements com.sun.jna.Structure.ByReference {}
	public static class ByValue extends CvScalar implements com.sun.jna.Structure.ByValue {}
}
