package cxcore;
/**
 * <i>native declaration : cxcore\include\cxtypes.h:1193</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.free.fr/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a>, <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class CvSetElem extends com.ochafik.lang.jnaerator.runtime.Structure {
	public int flags;
	public cxcore.CvSetElem.ByReference next_free;
	public CvSetElem() {
		super();
	}
	public CvSetElem(int flags, cxcore.CvSetElem.ByReference next_free) {
		super();
		this.flags = flags;
		this.next_free = next_free;
	}
	public ByReference byReference() { return setupClone(new ByReference()); }
	public ByValue byValue() { return setupClone(new ByValue()); }
	public CvSetElem clone() { return setupClone(new CvSetElem()); }
	public static class ByReference extends CvSetElem implements com.sun.jna.Structure.ByReference {}
	public static class ByValue extends CvSetElem implements com.sun.jna.Structure.ByValue {}
}
