package cxcore;
/**
 * <i>native declaration : cxcore\include\cxtypes.h:1138</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.free.fr/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a>, <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class CvSeqBlock extends com.ochafik.lang.jnaerator.runtime.Structure {
	/// Previous sequence block.
	public cxcore.CvSeqBlock.ByReference prev;
	/// Next sequence block.
	public cxcore.CvSeqBlock.ByReference next;
	/// Index of the first element in the block +
	public int start_index;
	/**
	 * sequence->first->start_index.<br>
	 * Number of elements in the block.
	 */
	public int count;
	/// Pointer to the first element of the block.
	public com.sun.jna.ptr.ByteByReference data;
	public CvSeqBlock() {
		super();
	}
	/**
	 * @param prev Previous sequence block.<br>
	 * @param next Next sequence block.<br>
	 * @param start_index Index of the first element in the block +<br>
	 * @param count sequence->first->start_index.<br>
	 * Number of elements in the block.<br>
	 * @param data Pointer to the first element of the block.
	 */
	public CvSeqBlock(cxcore.CvSeqBlock.ByReference prev, cxcore.CvSeqBlock.ByReference next, int start_index, int count, com.sun.jna.ptr.ByteByReference data) {
		super();
		this.prev = prev;
		this.next = next;
		this.start_index = start_index;
		this.count = count;
		this.data = data;
	}
	public ByReference byReference() { return setupClone(new ByReference()); }
	public ByValue byValue() { return setupClone(new ByValue()); }
	public CvSeqBlock clone() { return setupClone(new CvSeqBlock()); }
	public static class ByReference extends CvSeqBlock implements com.sun.jna.Structure.ByReference {}
	public static class ByValue extends CvSeqBlock implements com.sun.jna.Structure.ByValue {}
}
