package cxcore;
/**
 * <i>native declaration : cxcore\include\cxtypes.h:995</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.free.fr/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a>, <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class CvSize2D32f extends com.ochafik.lang.jnaerator.runtime.Structure {
	public float width;
	public float height;
	public CvSize2D32f() {
		super();
	}
	public CvSize2D32f(float width, float height) {
		super();
		this.width = width;
		this.height = height;
	}
	public ByReference byReference() { return setupClone(new ByReference()); }
	public ByValue byValue() { return setupClone(new ByValue()); }
	public CvSize2D32f clone() { return setupClone(new CvSize2D32f()); }
	public static class ByReference extends CvSize2D32f implements com.sun.jna.Structure.ByReference {}
	public static class ByValue extends CvSize2D32f implements com.sun.jna.Structure.ByValue {}
}
