package cxcore;
/**
 * <i>native declaration : cxcore\include\cxtypes.h:1042</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.free.fr/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a>, <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class CvSlice extends com.ochafik.lang.jnaerator.runtime.Structure {
	public int start_index;
	public int end_index;
	public CvSlice() {
		super();
	}
	public CvSlice(int start_index, int end_index) {
		super();
		this.start_index = start_index;
		this.end_index = end_index;
	}
	public ByReference byReference() { return setupClone(new ByReference()); }
	public ByValue byValue() { return setupClone(new ByValue()); }
	public CvSlice clone() { return setupClone(new CvSlice()); }
	public static class ByReference extends CvSlice implements com.sun.jna.Structure.ByReference {}
	public static class ByValue extends CvSlice implements com.sun.jna.Structure.ByValue {}
}
