package cxcore;
/**
 * <i>native declaration : cxcore\include\cxtypes.h:698</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.free.fr/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a>, <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class CvSparseMat extends com.ochafik.lang.jnaerator.runtime.Structure {
	public int type;
	public int dims;
	public com.sun.jna.ptr.IntByReference refcount;
	public int hdr_refcount;
	public cxcore.CvSet.ByReference heap;
	public com.sun.jna.ptr.PointerByReference hashtable;
	public int hashsize;
	public int valoffset;
	public int idxoffset;
	public int[] size = new int[(32)];
	public CvSparseMat() {
		super();
	}
	public ByReference byReference() { return setupClone(new ByReference()); }
	public ByValue byValue() { return setupClone(new ByValue()); }
	public CvSparseMat clone() { return setupClone(new CvSparseMat()); }
	public static class ByReference extends CvSparseMat implements com.sun.jna.Structure.ByReference {}
	public static class ByValue extends CvSparseMat implements com.sun.jna.Structure.ByValue {}
}
