package cxcore;
/**
 * <i>native declaration : cxcore\include\cxtypes.h:723</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.free.fr/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a>, <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class CvSparseNode extends com.ochafik.lang.jnaerator.runtime.Structure {
	public int hashval;
	public cxcore.CvSparseNode.ByReference next;
	public CvSparseNode() {
		super();
	}
	public CvSparseNode(int hashval, cxcore.CvSparseNode.ByReference next) {
		super();
		this.hashval = hashval;
		this.next = next;
	}
	public ByReference byReference() { return setupClone(new ByReference()); }
	public ByValue byValue() { return setupClone(new ByValue()); }
	public CvSparseNode clone() { return setupClone(new CvSparseNode()); }
	public static class ByReference extends CvSparseNode implements com.sun.jna.Structure.ByReference {}
	public static class ByValue extends CvSparseNode implements com.sun.jna.Structure.ByValue {}
}
