package cxcore;
/**
 * <i>native declaration : cxcore\include\cxtypes.h:730</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.free.fr/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a>, <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class CvSparseMatIterator extends com.ochafik.lang.jnaerator.runtime.Structure {
	public cxcore.CvSparseMat.ByReference mat;
	public cxcore.CvSparseNode.ByReference node;
	public int curidx;
	public CvSparseMatIterator() {
		super();
	}
	public CvSparseMatIterator(cxcore.CvSparseMat.ByReference mat, cxcore.CvSparseNode.ByReference node, int curidx) {
		super();
		this.mat = mat;
		this.node = node;
		this.curidx = curidx;
	}
	public ByReference byReference() { return setupClone(new ByReference()); }
	public ByValue byValue() { return setupClone(new ByValue()); }
	public CvSparseMatIterator clone() { return setupClone(new CvSparseMatIterator()); }
	public static class ByReference extends CvSparseMatIterator implements com.sun.jna.Structure.ByReference {}
	public static class ByValue extends CvSparseMatIterator implements com.sun.jna.Structure.ByValue {}
}
