package cxcore;
/**
 * <i>native declaration : cxcore\include\cxtypes.h:1644</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.free.fr/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a>, <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class CvString extends com.ochafik.lang.jnaerator.runtime.Structure {
	public int len;
	public com.sun.jna.ptr.ByteByReference ptr;
	public CvString() {
		super();
	}
	public CvString(int len, com.sun.jna.ptr.ByteByReference ptr) {
		super();
		this.len = len;
		this.ptr = ptr;
	}
	public ByReference byReference() { return setupClone(new ByReference()); }
	public ByValue byValue() { return setupClone(new ByValue()); }
	public CvString clone() { return setupClone(new CvString()); }
	public static class ByReference extends CvString implements com.sun.jna.Structure.ByReference {}
	public static class ByValue extends CvString implements com.sun.jna.Structure.ByValue {}
}
