package cxcore;
/**
 * <i>native declaration : cxcore\include\cxtypes.h:1653</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.free.fr/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a>, <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class CvStringHashNode extends com.ochafik.lang.jnaerator.runtime.Structure {
	public int hashval;
	public cxcore.CvString str;
	public cxcore.CvStringHashNode.ByReference next;
	public CvStringHashNode() {
		super();
	}
	public CvStringHashNode(int hashval, cxcore.CvString str, cxcore.CvStringHashNode.ByReference next) {
		super();
		this.hashval = hashval;
		this.str = str;
		this.next = next;
	}
	public ByReference byReference() { return setupClone(new ByReference()); }
	public ByValue byValue() { return setupClone(new ByValue()); }
	public CvStringHashNode clone() { return setupClone(new CvStringHashNode()); }
	public static class ByReference extends CvStringHashNode implements com.sun.jna.Structure.ByReference {}
	public static class ByValue extends CvStringHashNode implements com.sun.jna.Structure.ByValue {}
}
