package cxcore;
/**
 * <i>native declaration : cxcore\include\cxtypes.h:1693</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.free.fr/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a>, <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class CvTypeInfo extends com.ochafik.lang.jnaerator.runtime.Structure {
	public int flags;
	public int header_size;
	public cxcore.CvTypeInfo.ByReference prev;
	public cxcore.CvTypeInfo.ByReference next;
	public com.sun.jna.ptr.ByteByReference type_name;
	public cxcore.CxcoreLibrary.CvIsInstanceFunc is_instance;
	public cxcore.CxcoreLibrary.CvReleaseFunc release;
	public cxcore.CxcoreLibrary.CvReadFunc read;
	public cxcore.CxcoreLibrary.CvWriteFunc write;
	public cxcore.CxcoreLibrary.CvCloneFunc clone;
	public CvTypeInfo() {
		super();
	}
	public ByReference byReference() { return setupClone(new ByReference()); }
	public ByValue byValue() { return setupClone(new ByValue()); }
	public CvTypeInfo clone() { return setupClone(new CvTypeInfo()); }
	public static class ByReference extends CvTypeInfo implements com.sun.jna.Structure.ByReference {}
	public static class ByValue extends CvTypeInfo implements com.sun.jna.Structure.ByValue {}
}
