package cxcore;
/**
 * <i>native declaration : cxcore\include\cxtypes.h:366</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.free.fr/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a>, <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class IplConvKernel extends com.ochafik.lang.jnaerator.runtime.Structure {
	public int nCols;
	public int nRows;
	public int anchorX;
	public int anchorY;
	public com.sun.jna.ptr.IntByReference values;
	public int nShiftR;
	public IplConvKernel() {
		super();
	}
	public IplConvKernel(int nCols, int nRows, int anchorX, int anchorY, com.sun.jna.ptr.IntByReference values, int nShiftR) {
		super();
		this.nCols = nCols;
		this.nRows = nRows;
		this.anchorX = anchorX;
		this.anchorY = anchorY;
		this.values = values;
		this.nShiftR = nShiftR;
	}
	public ByReference byReference() { return setupClone(new ByReference()); }
	public ByValue byValue() { return setupClone(new ByValue()); }
	public IplConvKernel clone() { return setupClone(new IplConvKernel()); }
	public static class ByReference extends IplConvKernel implements com.sun.jna.Structure.ByReference {}
	public static class ByValue extends IplConvKernel implements com.sun.jna.Structure.ByValue {}
}
