package cxcore;
/**
 * <i>native declaration : cxcore\include\cxtypes.h:356</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.free.fr/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a>, <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class IplROI extends com.ochafik.lang.jnaerator.runtime.Structure {
	/// 0 - no COI (all channels are selected), 1 - 0th channel is selected ...
	public int coi;
	public int xOffset;
	public int yOffset;
	public int width;
	public int height;
	public IplROI() {
		super();
	}
	/// @param coi 0 - no COI (all channels are selected), 1 - 0th channel is selected ...
	public IplROI(int coi, int xOffset, int yOffset, int width, int height) {
		super();
		this.coi = coi;
		this.xOffset = xOffset;
		this.yOffset = yOffset;
		this.width = width;
		this.height = height;
	}
	public ByReference byReference() { return setupClone(new ByReference()); }
	public ByValue byValue() { return setupClone(new ByValue()); }
	public IplROI clone() { return setupClone(new IplROI()); }
	public static class ByReference extends IplROI implements com.sun.jna.Structure.ByReference {}
	public static class ByValue extends IplROI implements com.sun.jna.Structure.ByValue {}
}
