package cvaux;
/**
 * <i>native declaration : cvaux\include\cvaux.h:849</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.free.fr/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a>, <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class Cv3dTracker2dTrackedObject extends com.ochafik.lang.jnaerator.runtime.Structure {
	public int id;
	/// pgruebele: So we do not loose precision, this needs to be float
	public cxcore.CvPoint2D32f p;
	public Cv3dTracker2dTrackedObject() {
		super();
	}
	/// @param p pgruebele: So we do not loose precision, this needs to be float
	public Cv3dTracker2dTrackedObject(int id, cxcore.CvPoint2D32f p) {
		super();
		this.id = id;
		this.p = p;
	}
	public ByReference byReference() { return setupClone(new ByReference()); }
	public ByValue byValue() { return setupClone(new ByValue()); }
	public Cv3dTracker2dTrackedObject clone() { return setupClone(new Cv3dTracker2dTrackedObject()); }
	public static class ByReference extends Cv3dTracker2dTrackedObject implements com.sun.jna.Structure.ByReference {}
	public static class ByValue extends Cv3dTracker2dTrackedObject implements com.sun.jna.Structure.ByValue {}
}
