package cvaux;
/**
 * <i>native declaration : cvaux\include\cvaux.h:1165</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.free.fr/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a>, <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class CvBGStatModel extends com.ochafik.lang.jnaerator.runtime.Structure {
	public int type;
	public cvaux.CvauxLibrary.CvReleaseBGStatModel release;
	public cvaux.CvauxLibrary.CvUpdateBGStatModel update;
	public cxcore.IplImage.ByReference background;
	public cxcore.IplImage.ByReference foreground;
	public cxcore.IplImage.ByReference[] layers;
	public int layer_count;
	public cxcore.CvMemStorage.ByReference storage;
	public cxcore.CvSeq.ByReference foreground_regions;
	public CvBGStatModel() {
		super();
	}
	public CvBGStatModel(int type, cvaux.CvauxLibrary.CvReleaseBGStatModel release, cvaux.CvauxLibrary.CvUpdateBGStatModel update, cxcore.IplImage.ByReference background, cxcore.IplImage.ByReference foreground, cxcore.IplImage.ByReference layers[], int layer_count, cxcore.CvMemStorage.ByReference storage, cxcore.CvSeq.ByReference foreground_regions) {
		super();
		this.type = type;
		this.release = release;
		this.update = update;
		this.background = background;
		this.foreground = foreground;
		if (layers.length != this.layers.length) 
			throw new java.lang.IllegalArgumentException("Wrong array size !");
		this.layers = layers;
		this.layer_count = layer_count;
		this.storage = storage;
		this.foreground_regions = foreground_regions;
	}
	public ByReference byReference() { return setupClone(new ByReference()); }
	public ByValue byValue() { return setupClone(new ByValue()); }
	public CvBGStatModel clone() { return setupClone(new CvBGStatModel()); }
	public static class ByReference extends CvBGStatModel implements com.sun.jna.Structure.ByReference {}
	public static class ByValue extends CvBGStatModel implements com.sun.jna.Structure.ByValue {}
}
