package cvaux;
/**
 * <i>native declaration : cvaux\include\cvaux.h:1276</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.free.fr/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a>, <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class CvBGPixelCCStatTable extends com.ochafik.lang.jnaerator.runtime.Structure {
	public float Pv;
	public float Pvb;
	public byte[] v = new byte[(6)];
	public CvBGPixelCCStatTable() {
		super();
	}
	public CvBGPixelCCStatTable(float Pv, float Pvb, byte v[]) {
		super();
		this.Pv = Pv;
		this.Pvb = Pvb;
		if (v.length != this.v.length) 
			throw new java.lang.IllegalArgumentException("Wrong array size !");
		this.v = v;
	}
	public ByReference byReference() { return setupClone(new ByReference()); }
	public ByValue byValue() { return setupClone(new ByValue()); }
	public CvBGPixelCCStatTable clone() { return setupClone(new CvBGPixelCCStatTable()); }
	public static class ByReference extends CvBGPixelCCStatTable implements com.sun.jna.Structure.ByReference {}
	public static class ByValue extends CvBGPixelCCStatTable implements com.sun.jna.Structure.ByValue {}
}
