package cvaux;
/**
 * <i>native declaration : cvaux\include\cvaux.h:1283</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.free.fr/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a>, <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class CvBGPixelStat extends com.ochafik.lang.jnaerator.runtime.Structure {
	public float Pbc;
	public float Pbcc;
	public cvaux.CvBGPixelCStatTable.ByReference ctable;
	public cvaux.CvBGPixelCCStatTable.ByReference cctable;
	public byte is_trained_st_model;
	public byte is_trained_dyn_model;
	public CvBGPixelStat() {
		super();
	}
	public CvBGPixelStat(float Pbc, float Pbcc, cvaux.CvBGPixelCStatTable.ByReference ctable, cvaux.CvBGPixelCCStatTable.ByReference cctable, byte is_trained_st_model, byte is_trained_dyn_model) {
		super();
		this.Pbc = Pbc;
		this.Pbcc = Pbcc;
		this.ctable = ctable;
		this.cctable = cctable;
		this.is_trained_st_model = is_trained_st_model;
		this.is_trained_dyn_model = is_trained_dyn_model;
	}
	public ByReference byReference() { return setupClone(new ByReference()); }
	public ByValue byValue() { return setupClone(new ByValue()); }
	public CvBGPixelStat clone() { return setupClone(new CvBGPixelStat()); }
	public static class ByReference extends CvBGPixelStat implements com.sun.jna.Structure.ByReference {}
	public static class ByValue extends CvBGPixelStat implements com.sun.jna.Structure.ByValue {}
}
