package cvaux;
/**
 * <i>native declaration : cvaux\include\cvaux.h:1374</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.free.fr/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a>, <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class CvBGCodeBookElem extends com.ochafik.lang.jnaerator.runtime.Structure {
	public cvaux.CvBGCodeBookElem.ByReference next;
	public int tLastUpdate;
	public int stale;
	public byte[] boxMin = new byte[(3)];
	public byte[] boxMax = new byte[(3)];
	public byte[] learnMin = new byte[(3)];
	public byte[] learnMax = new byte[(3)];
	public CvBGCodeBookElem() {
		super();
	}
	public CvBGCodeBookElem(cvaux.CvBGCodeBookElem.ByReference next, int tLastUpdate, int stale, byte boxMin[], byte boxMax[], byte learnMin[], byte learnMax[]) {
		super();
		this.next = next;
		this.tLastUpdate = tLastUpdate;
		this.stale = stale;
		if (boxMin.length != this.boxMin.length) 
			throw new java.lang.IllegalArgumentException("Wrong array size !");
		this.boxMin = boxMin;
		if (boxMax.length != this.boxMax.length) 
			throw new java.lang.IllegalArgumentException("Wrong array size !");
		this.boxMax = boxMax;
		if (learnMin.length != this.learnMin.length) 
			throw new java.lang.IllegalArgumentException("Wrong array size !");
		this.learnMin = learnMin;
		if (learnMax.length != this.learnMax.length) 
			throw new java.lang.IllegalArgumentException("Wrong array size !");
		this.learnMax = learnMax;
	}
	public ByReference byReference() { return setupClone(new ByReference()); }
	public ByValue byValue() { return setupClone(new ByValue()); }
	public CvBGCodeBookElem clone() { return setupClone(new CvBGCodeBookElem()); }
	public static class ByReference extends CvBGCodeBookElem implements com.sun.jna.Structure.ByReference {}
	public static class ByValue extends CvBGCodeBookElem implements com.sun.jna.Structure.ByValue {}
}
