package cvaux;
/**
 * <i>native declaration : cvaux\include\cvaux.h:1386</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.free.fr/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a>, <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class CvBGCodeBookModel extends com.ochafik.lang.jnaerator.runtime.Structure {
	public cxcore.CvSize size;
	public int t;
	public byte[] cbBounds = new byte[(3)];
	public byte[] modMin = new byte[(3)];
	public byte[] modMax = new byte[(3)];
	public cvaux.CvBGCodeBookElem.ByReference[] cbmap;
	public cxcore.CvMemStorage.ByReference storage;
	public cvaux.CvBGCodeBookElem.ByReference freeList;
	public CvBGCodeBookModel() {
		super();
	}
	public CvBGCodeBookModel(cxcore.CvSize size, int t, byte cbBounds[], byte modMin[], byte modMax[], cvaux.CvBGCodeBookElem.ByReference cbmap[], cxcore.CvMemStorage.ByReference storage, cvaux.CvBGCodeBookElem.ByReference freeList) {
		super();
		this.size = size;
		this.t = t;
		if (cbBounds.length != this.cbBounds.length) 
			throw new java.lang.IllegalArgumentException("Wrong array size !");
		this.cbBounds = cbBounds;
		if (modMin.length != this.modMin.length) 
			throw new java.lang.IllegalArgumentException("Wrong array size !");
		this.modMin = modMin;
		if (modMax.length != this.modMax.length) 
			throw new java.lang.IllegalArgumentException("Wrong array size !");
		this.modMax = modMax;
		if (cbmap.length != this.cbmap.length) 
			throw new java.lang.IllegalArgumentException("Wrong array size !");
		this.cbmap = cbmap;
		this.storage = storage;
		this.freeList = freeList;
	}
	public ByReference byReference() { return setupClone(new ByReference()); }
	public ByValue byValue() { return setupClone(new ByValue()); }
	public CvBGCodeBookModel clone() { return setupClone(new CvBGCodeBookModel()); }
	public static class ByReference extends CvBGCodeBookModel implements com.sun.jna.Structure.ByReference {}
	public static class ByValue extends CvBGCodeBookModel implements com.sun.jna.Structure.ByValue {}
}
