package cvaux;
/**
 * <i>native declaration : cvaux\include\cvaux.h:832</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.free.fr/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a>, <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class CvFace extends com.ochafik.lang.jnaerator.runtime.Structure {
	public cxcore.CvRect MouthRect;
	public cxcore.CvRect LeftEyeRect;
	public cxcore.CvRect RightEyeRect;
	public CvFace() {
		super();
	}
	public CvFace(cxcore.CvRect MouthRect, cxcore.CvRect LeftEyeRect, cxcore.CvRect RightEyeRect) {
		super();
		this.MouthRect = MouthRect;
		this.LeftEyeRect = LeftEyeRect;
		this.RightEyeRect = RightEyeRect;
	}
	public ByReference byReference() { return setupClone(new ByReference()); }
	public ByValue byValue() { return setupClone(new ByValue()); }
	public CvFace clone() { return setupClone(new CvFace()); }
	public static class ByReference extends CvFace implements com.sun.jna.Structure.ByReference {}
	public static class ByValue extends CvFace implements com.sun.jna.Structure.ByValue {}
}
