package cvaux;
/**
 * <i>native declaration : cvaux\include\cvaux.h:1243</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.free.fr/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a>, <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class CvFGDStatModelParams extends com.ochafik.lang.jnaerator.runtime.Structure {
	/// Quantized levels per 'color' component. Power of two, typically 32, 64 or 128.
	public int Lc;
	/// Number of color vectors used to model normal background color variation at a given pixel.
	public int N1c;
	/// Number of color vectors retained at given pixel.  Must be > N1c, typically ~ 5/3 of N1c.
	public int N2c;
	/// Quantized levels per 'color co-occurrence' component.  Power of two, typically 16, 32 or 64.
	public int Lcc;
	/// Number of color co-occurrence vectors used to model normal background color variation at a given pixel.
	public int N1cc;
	/// Number of color co-occurrence vectors retained at given pixel.  Must be > N1cc, typically ~ 5/3 of N1cc.
	public int N2cc;
	/// If TRUE we ignore holes within foreground blobs. Defaults to TRUE.
	public int is_obj_without_holes;
	/// Number of erode-dilate-erode foreground-blob cleanup iterations.
	public int perform_morphing;
	/// How quickly we forget old background pixel values seen.  Typically set to 0.1
	public float alpha1;
	/// "Controls speed of feature learning". Depends on T. Typical value circa 0.005.
	public float alpha2;
	/// Alternate to alpha2, used (e.g.) for quicker initial convergence. Typical value 0.1.
	public float alpha3;
	/// Affects color and color co-occurrence quantization, typically set to 2.
	public float delta;
	/// "A percentage value which determines when new features can be recognized as new background." (Typically 0.9).
	public float T;
	/// Discard foreground blobs whose bounding box is smaller than this threshold.
	public float minArea;
	public CvFGDStatModelParams() {
		super();
	}
	public ByReference byReference() { return setupClone(new ByReference()); }
	public ByValue byValue() { return setupClone(new ByValue()); }
	public CvFGDStatModelParams clone() { return setupClone(new CvFGDStatModelParams()); }
	public static class ByReference extends CvFGDStatModelParams implements com.sun.jna.Structure.ByReference {}
	public static class ByValue extends CvFGDStatModelParams implements com.sun.jna.Structure.ByValue {}
}
