package cvaux;
/**
 * <i>native declaration : cvaux\include\cvaux.h:1295</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.free.fr/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a>, <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class CvFGDStatModel extends com.ochafik.lang.jnaerator.runtime.Structure {
	public int type;
	public cvaux.CvauxLibrary.CvReleaseBGStatModel release;
	public cvaux.CvauxLibrary.CvUpdateBGStatModel update;
	public cxcore.IplImage.ByReference background;
	public cxcore.IplImage.ByReference foreground;
	public cxcore.IplImage.ByReference[] layers;
	public int layer_count;
	public cxcore.CvMemStorage.ByReference storage;
	public cxcore.CvSeq.ByReference foreground_regions;
	public cvaux.CvBGPixelStat.ByReference pixel_stat;
	public cxcore.IplImage.ByReference Ftd;
	public cxcore.IplImage.ByReference Fbd;
	public cxcore.IplImage.ByReference prev_frame;
	public cvaux.CvFGDStatModelParams params;
	public CvFGDStatModel() {
		super();
	}
	public ByReference byReference() { return setupClone(new ByReference()); }
	public ByValue byValue() { return setupClone(new ByValue()); }
	public CvFGDStatModel clone() { return setupClone(new CvFGDStatModel()); }
	public static class ByReference extends CvFGDStatModel implements com.sun.jna.Structure.ByReference {}
	public static class ByValue extends CvFGDStatModel implements com.sun.jna.Structure.ByValue {}
}
