package cvaux;
/**
 * <i>native declaration : cvaux\include\cvaux.h:1343</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.free.fr/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a>, <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class CvGaussBGValues extends com.ochafik.lang.jnaerator.runtime.Structure {
	public int match_sum;
	public double weight;
	public double[] variance = new double[(3)];
	public double[] mean = new double[(3)];
	public CvGaussBGValues() {
		super();
	}
	public CvGaussBGValues(int match_sum, double weight, double variance[], double mean[]) {
		super();
		this.match_sum = match_sum;
		this.weight = weight;
		if (variance.length != this.variance.length) 
			throw new java.lang.IllegalArgumentException("Wrong array size !");
		this.variance = variance;
		if (mean.length != this.mean.length) 
			throw new java.lang.IllegalArgumentException("Wrong array size !");
		this.mean = mean;
	}
	public ByReference byReference() { return setupClone(new ByReference()); }
	public ByValue byValue() { return setupClone(new ByValue()); }
	public CvGaussBGValues clone() { return setupClone(new CvGaussBGValues()); }
	public static class ByReference extends CvGaussBGValues implements com.sun.jna.Structure.ByReference {}
	public static class ByValue extends CvGaussBGValues implements com.sun.jna.Structure.ByValue {}
}
