package cvaux;
/**
 * <i>native declaration : cvaux\include\cvaux.h:1352</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.free.fr/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a>, <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class CvGaussBGPoint extends com.ochafik.lang.jnaerator.runtime.Structure {
	public cvaux.CvGaussBGValues.ByReference g_values;
	public CvGaussBGPoint() {
		super();
	}
	public CvGaussBGPoint(cvaux.CvGaussBGValues.ByReference g_values) {
		super();
		this.g_values = g_values;
	}
	public ByReference byReference() { return setupClone(new ByReference()); }
	public ByValue byValue() { return setupClone(new ByValue()); }
	public CvGaussBGPoint clone() { return setupClone(new CvGaussBGPoint()); }
	public static class ByReference extends CvGaussBGPoint implements com.sun.jna.Structure.ByReference {}
	public static class ByValue extends CvGaussBGPoint implements com.sun.jna.Structure.ByValue {}
}
