package cvaux;
/**
 * <i>native declaration : cvaux\include\cvaux.h:279</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.free.fr/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a>, <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class CvGraphWeightedVtx extends com.ochafik.lang.jnaerator.runtime.Structure {
	public int flags;
	public cxcore.CvGraphEdge.ByReference first;
	public float weight;
	public CvGraphWeightedVtx() {
		super();
	}
	public CvGraphWeightedVtx(int flags, cxcore.CvGraphEdge.ByReference first, float weight) {
		super();
		this.flags = flags;
		this.first = first;
		this.weight = weight;
	}
	public ByReference byReference() { return setupClone(new ByReference()); }
	public ByValue byValue() { return setupClone(new ByValue()); }
	public CvGraphWeightedVtx clone() { return setupClone(new CvGraphWeightedVtx()); }
	public static class ByReference extends CvGraphWeightedVtx implements com.sun.jna.Structure.ByReference {}
	public static class ByValue extends CvGraphWeightedVtx implements com.sun.jna.Structure.ByValue {}
}
