package cvaux;
/**
 * <i>native declaration : cvaux\include\cvaux.h:56</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.free.fr/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a>, <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class CvInput extends com.ochafik.lang.jnaerator.runtime.Union {
	public cvaux.CvauxLibrary.CvCallback callback;
	public com.sun.jna.Pointer data;
	public CvInput() {
		super();
	}
	public CvInput(cvaux.CvauxLibrary.CvCallback callback) {
		super();
		this.callback = callback;
		setType(cvaux.CvauxLibrary.CvCallback.class);
	}
	public CvInput(com.sun.jna.Pointer data) {
		super();
		this.data = data;
		setType(com.sun.jna.Pointer.class);
	}
	public ByReference byReference() { return setupClone(new ByReference()); }
	public ByValue byValue() { return setupClone(new ByValue()); }
	public CvInput clone() { return setupClone(new CvInput()); }
	public static class ByReference extends CvInput implements com.sun.jna.Structure.ByReference {}
	public static class ByValue extends CvInput implements com.sun.jna.Structure.ByValue {}
}
