package cvaux;
/**
 * <i>native declaration : cvaux\include\cvaux.h:1010</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.free.fr/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a>, <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class CvLCMNode extends com.ochafik.lang.jnaerator.runtime.Structure {
	public int flags;
	public cxcore.CvGraphEdge.ByReference first;
	public cxcore.CvContour.ByReference contour;
	public CvLCMNode() {
		super();
	}
	public CvLCMNode(int flags, cxcore.CvGraphEdge.ByReference first, cxcore.CvContour.ByReference contour) {
		super();
		this.flags = flags;
		this.first = first;
		this.contour = contour;
	}
	public ByReference byReference() { return setupClone(new ByReference()); }
	public ByValue byValue() { return setupClone(new ByValue()); }
	public CvLCMNode clone() { return setupClone(new CvLCMNode()); }
	public static class ByReference extends CvLCMNode implements com.sun.jna.Structure.ByReference {}
	public static class ByValue extends CvLCMNode implements com.sun.jna.Structure.ByValue {}
}
