package cvaux;
/**
 * <i>native declaration : cvaux\include\cvaux.h:485</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.free.fr/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a>, <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class CvStereoLineCoeff extends com.ochafik.lang.jnaerator.runtime.Structure {
	public double Xcoef;
	public double XcoefA;
	public double XcoefB;
	public double XcoefAB;
	public double Ycoef;
	public double YcoefA;
	public double YcoefB;
	public double YcoefAB;
	public double Zcoef;
	public double ZcoefA;
	public double ZcoefB;
	public double ZcoefAB;
	public CvStereoLineCoeff() {
		super();
	}
	public ByReference byReference() { return setupClone(new ByReference()); }
	public ByValue byValue() { return setupClone(new ByValue()); }
	public CvStereoLineCoeff clone() { return setupClone(new CvStereoLineCoeff()); }
	public static class ByReference extends CvStereoLineCoeff implements com.sun.jna.Structure.ByReference {}
	public static class ByValue extends CvStereoLineCoeff implements com.sun.jna.Structure.ByValue {}
}
