package cvaux;
/**
 * <i>native declaration : cvaux\include\cvaux.h:941</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.free.fr/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a>, <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class CvVoronoiSite2D extends com.ochafik.lang.jnaerator.runtime.Structure {
	public cvaux.CvVoronoiNode2D.ByReference[] node = new cvaux.CvVoronoiNode2D.ByReference[(2)];
	public cvaux.CvVoronoiEdge2D.ByReference[] edge = new cvaux.CvVoronoiEdge2D.ByReference[(2)];
	public cvaux.CvVoronoiSite2D.ByReference[] next = new cvaux.CvVoronoiSite2D.ByReference[(2)];
	public CvVoronoiSite2D() {
		super();
	}
	public CvVoronoiSite2D(cvaux.CvVoronoiNode2D.ByReference node[], cvaux.CvVoronoiEdge2D.ByReference edge[], cvaux.CvVoronoiSite2D.ByReference next[]) {
		super();
		if (node.length != this.node.length) 
			throw new java.lang.IllegalArgumentException("Wrong array size !");
		this.node = node;
		if (edge.length != this.edge.length) 
			throw new java.lang.IllegalArgumentException("Wrong array size !");
		this.edge = edge;
		if (next.length != this.next.length) 
			throw new java.lang.IllegalArgumentException("Wrong array size !");
		this.next = next;
	}
	public ByReference byReference() { return setupClone(new ByReference()); }
	public ByValue byValue() { return setupClone(new ByValue()); }
	public CvVoronoiSite2D clone() { return setupClone(new CvVoronoiSite2D()); }
	public static class ByReference extends CvVoronoiSite2D implements com.sun.jna.Structure.ByReference {}
	public static class ByValue extends CvVoronoiSite2D implements com.sun.jna.Structure.ByValue {}
}
