package cvaux;
/**
 * <i>native declaration : cvaux\include\cvaux.h:962</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.free.fr/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a>, <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class CvVoronoiNode2D extends com.ochafik.lang.jnaerator.runtime.Structure {
	public int flags;
	public cvaux.CvVoronoiNode2D.ByReference next_free;
	public cxcore.CvPoint2D32f pt;
	public float radius;
	public CvVoronoiNode2D() {
		super();
	}
	public CvVoronoiNode2D(int flags, cvaux.CvVoronoiNode2D.ByReference next_free, cxcore.CvPoint2D32f pt, float radius) {
		super();
		this.flags = flags;
		this.next_free = next_free;
		this.pt = pt;
		this.radius = radius;
	}
	public ByReference byReference() { return setupClone(new ByReference()); }
	public ByValue byValue() { return setupClone(new ByValue()); }
	public CvVoronoiNode2D clone() { return setupClone(new CvVoronoiNode2D()); }
	public static class ByReference extends CvVoronoiNode2D implements com.sun.jna.Structure.ByReference {}
	public static class ByValue extends CvVoronoiNode2D implements com.sun.jna.Structure.ByValue {}
}
