package cvaux;
/**
 * <i>native declaration : cvaux\include\cvaux.h:952</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.free.fr/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a>, <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class CvVoronoiEdge2D extends com.ochafik.lang.jnaerator.runtime.Structure {
	public cvaux.CvVoronoiNode2D.ByReference[] node = new cvaux.CvVoronoiNode2D.ByReference[(2)];
	public cvaux.CvVoronoiSite2D.ByReference[] site = new cvaux.CvVoronoiSite2D.ByReference[(2)];
	public cvaux.CvVoronoiEdge2D.ByReference[] next = new cvaux.CvVoronoiEdge2D.ByReference[(4)];
	public CvVoronoiEdge2D() {
		super();
	}
	public CvVoronoiEdge2D(cvaux.CvVoronoiNode2D.ByReference node[], cvaux.CvVoronoiSite2D.ByReference site[], cvaux.CvVoronoiEdge2D.ByReference next[]) {
		super();
		if (node.length != this.node.length) 
			throw new java.lang.IllegalArgumentException("Wrong array size !");
		this.node = node;
		if (site.length != this.site.length) 
			throw new java.lang.IllegalArgumentException("Wrong array size !");
		this.site = site;
		if (next.length != this.next.length) 
			throw new java.lang.IllegalArgumentException("Wrong array size !");
		this.next = next;
	}
	public ByReference byReference() { return setupClone(new ByReference()); }
	public ByValue byValue() { return setupClone(new ByValue()); }
	public CvVoronoiEdge2D clone() { return setupClone(new CvVoronoiEdge2D()); }
	public static class ByReference extends CvVoronoiEdge2D implements com.sun.jna.Structure.ByReference {}
	public static class ByValue extends CvVoronoiEdge2D implements com.sun.jna.Structure.ByValue {}
}
