/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ru_nickl_meanshift_direct_cuda_NativeCudaMSFilter */

#ifndef _Included_ru_nickl_meanshift_direct_cuda_NativeCudaMSFilter
#define _Included_ru_nickl_meanshift_direct_cuda_NativeCudaMSFilter
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ru_nickl_meanshift_direct_cuda_NativeCudaMSFilter
 * Method:    doNativefilter
 * Signature: ([D[DIISD)V
 */
JNIEXPORT void JNICALL Java_ru_nickl_meanshift_direct_cuda_NativeCudaMSFilter_doNativefilter
  (JNIEnv *, jobject, jdoubleArray, jdoubleArray, jint, jint, jshort, jdouble, jint);

#ifdef __cplusplus
}
#endif
#endif
