/*
 *
 * This file is part of Aiphial.
 *
 * Copyright (c) 2010 Nicolay Mitropolsky <NicolayMitropolsky@gmail.com>
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as published by
 * the Free Software Foundation, either version 2 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 *
 */

package me.uits.aiphial.imaging.texture

import me.uits.aiphial.imaging.Matrix
import scala.io.Source
import scala.util.parsing.json.JSON

object Gabor {

  /**
   * generated by gaboratfer-v1.0 gabor.py
   */
 
  val gaborFiltres9 = readfromjs("g9.js")

  val gaborFiltres15 = readfromjs("g15.js")


  private def readfromjs(js:String) ={
    val addr = Gabor.getClass.getResourceAsStream(js)
    val input = Source.fromInputStream(addr).mkString

    addr.close

    JSON.parseFull(input) match {
      case Some(a:List[List[List[Double]]]) => a.toArray.map(_.toArray.map(_.toArray))
      case None => throw new RuntimeException("cant parse")
    }
  }

    

  val gaborMatrix ={
    val gaborMatrix9 = Gabor.gaborFiltres9.map(Matrix(_))
    val gaborMatrix15 = Gabor.gaborFiltres15.map(Matrix(_))          
    
    gaborMatrix9.map(_.addBorder(3, 3, 0))++gaborMatrix15}


}
