/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

package me.uits.aiphial.imaging.texture

import me.uits.aiphial.imaging.Matrix
import scala.io.Source
import scala.util.parsing.json.JSON

object Gabor {

  /**
   * generated by gaboratfer-v1.0 gabor.py
   */
 
  val gaborFiltres9 = readfromjs("g9.js")

  val gaborFiltres15 = readfromjs("g15.js")


  private def readfromjs(js:String) ={
    val addr = Gabor.getClass.getResourceAsStream(js)
    val input = Source.fromInputStream(addr).mkString

    addr.close

    JSON.parseFull(input) match {
      case Some(a:List[List[List[Double]]]) => a.toArray.map(_.toArray.map(_.toArray))
      case None => throw new RuntimeException("cant parse")
    }
  }

    

  val gaborMatrix ={
    val gaborMatrix9 = Gabor.gaborFiltres9.map(Matrix(_))
    val gaborMatrix15 = Gabor.gaborFiltres15.map(Matrix(_))          
    
    gaborMatrix9.map(_.addBorder(3, 3, 0))++gaborMatrix15}


}
