package ml;
/**
 * <i>native declaration : ml\include\ml.h:117</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.free.fr/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a>, <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class CvVectors extends com.ochafik.lang.jnaerator.runtime.Structure {
	public int type;
	public int dims;
	public int count;
	public ml.CvVectors.ByReference next;
	public data_union data;
	/// <i>native declaration : ml\include\ml.h:122</i>
	public static class data_union extends com.ochafik.lang.jnaerator.runtime.Union {
		public com.sun.jna.ptr.PointerByReference ptr;
		public com.sun.jna.ptr.PointerByReference fl;
		public com.sun.jna.ptr.PointerByReference db;
		public data_union() {
			super();
		}
		public data_union(com.sun.jna.ptr.PointerByReference ptr_or_fl_or_db) {
			super();
			this.db = this.fl = this.ptr = ptr_or_fl_or_db;
			setType(com.sun.jna.ptr.PointerByReference.class);
		}
		public ByReference byReference() { return setupClone(new ByReference()); }
		public ByValue byValue() { return setupClone(new ByValue()); }
		public data_union clone() { return setupClone(new data_union()); }
		public static class ByReference extends data_union implements com.sun.jna.Structure.ByReference {}
		public static class ByValue extends data_union implements com.sun.jna.Structure.ByValue {}
	}
	public CvVectors() {
		super();
	}
	public CvVectors(int type, int dims, int count, ml.CvVectors.ByReference next, data_union data) {
		super();
		this.type = type;
		this.dims = dims;
		this.count = count;
		this.next = next;
		this.data = data;
	}
	public ByReference byReference() { return setupClone(new ByReference()); }
	public ByValue byValue() { return setupClone(new ByValue()); }
	public CvVectors clone() { return setupClone(new CvVectors()); }
	public static class ByReference extends CvVectors implements com.sun.jna.Structure.ByReference {}
	public static class ByValue extends CvVectors implements com.sun.jna.Structure.ByValue {}
}
