package highgui;
/**
 * <i>native declaration : otherlibs\highgui\gstappsink.h:33</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.free.fr/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a>, <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class _GstAppSinkClass extends com.ochafik.lang.jnaerator.runtime.Structure {
	/// Conversion Error : GstBaseSinkClass
	/// actions
	public highgui._GstAppSinkClass.pull_preroll_callback pull_preroll;
	public highgui._GstAppSinkClass.pull_buffer_callback pull_buffer;
	/// <i>native declaration : otherlibs\highgui\gstappsink.h</i>
	public interface gboolean_callback extends com.sun.jna.Callback {
		int invoke(highgui._GstAppSink sink);
	}
	/// <i>native declaration : otherlibs\highgui\gstappsink.h</i>
	public interface gboolean_callback2 extends com.sun.jna.Callback {
		int invoke(highgui._GstAppSink sink);
	}
	/// <i>native declaration : otherlibs\highgui\gstappsink.h</i>
	public interface gboolean_callback3 extends com.sun.jna.Callback {
		int invoke(highgui._GstAppSink sink);
	}
	/// <i>native declaration : otherlibs\highgui\gstappsink.h:43</i>
	public interface pull_preroll_callback extends com.sun.jna.Callback {
		highgui.HighguiLibrary.GstBuffer invoke(highgui._GstAppSink sink);
	}
	/// <i>native declaration : otherlibs\highgui\gstappsink.h:44</i>
	public interface pull_buffer_callback extends com.sun.jna.Callback {
		highgui.HighguiLibrary.GstBuffer invoke(highgui._GstAppSink sink);
	}
	public _GstAppSinkClass() {
		super();
	}
	/// @param pull_preroll actions
	public _GstAppSinkClass(highgui._GstAppSinkClass.pull_preroll_callback pull_preroll, highgui._GstAppSinkClass.pull_buffer_callback pull_buffer) {
		super();
		this.pull_preroll = pull_preroll;
		this.pull_buffer = pull_buffer;
	}
	public ByReference byReference() { return setupClone(new ByReference()); }
	public ByValue byValue() { return setupClone(new ByValue()); }
	public _GstAppSinkClass clone() { return setupClone(new _GstAppSinkClass()); }
	public static class ByReference extends _GstAppSinkClass implements com.sun.jna.Structure.ByReference {}
	public static class ByValue extends _GstAppSinkClass implements com.sun.jna.Structure.ByValue {}
}
