package highgui;
/**
 * <i>native declaration : otherlibs\highgui\_highgui.h:30</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.free.fr/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a>, <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class CvVideoWriter extends com.ochafik.lang.jnaerator.runtime.Structure {
	public CvVideoWriter() {
		super();
	}
	public ByReference byReference() { return setupClone(new ByReference()); }
	public ByValue byValue() { return setupClone(new ByValue()); }
	public CvVideoWriter clone() { return setupClone(new CvVideoWriter()); }
	public static class ByReference extends CvVideoWriter implements com.sun.jna.Structure.ByReference {}
	public static class ByValue extends CvVideoWriter implements com.sun.jna.Structure.ByValue {}
}
