package highgui;
/**
 * JNA Wrapper for library <b>highgui</b><br>
 * @see OpenCV.highgui<br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.free.fr/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a>, <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public interface HighguiLibrary extends com.sun.jna.Library {
	/**
	 * <i>native declaration : otherlibs\highgui\grfmt_bmp.h:42</i><br>
	 * enum values
	 */
	public static interface BmpCompression {
		public static final int BMP_RGB = 0;
		public static final int BMP_RLE8 = 1;
		public static final int BMP_RLE4 = 2;
		public static final int BMP_BITFIELDS = 3;
	}
	/**
	 * <i>native declaration : otherlibs\highgui\grfmt_sunras.h:42</i><br>
	 * enum values
	 */
	public static interface SunRasType {
		public static final int RAS_OLD = 0;
		public static final int RAS_STANDARD = 1;
		/// RLE encoded
		public static final int RAS_BYTE_ENCODED = 2;
		/// RGB instead of BGR
		public static final int RAS_FORMAT_RGB = 3;
	}
	/**
	 * <i>native declaration : otherlibs\highgui\grfmt_sunras.h:50</i><br>
	 * enum values
	 */
	public static interface SunRasMapType {
		/// direct color encoding
		public static final int RMT_NONE = 0;
		/// paletted image
		public static final int RMT_EQUAL_RGB = 1;
	}
	/**
	 * native simple TIFF codec<br>
	 * <i>native declaration : otherlibs\highgui\grfmt_tiff.h:44</i><br>
	 * enum values
	 */
	public static interface TiffCompression {
		public static final int TIFF_UNCOMP = 1;
		public static final int TIFF_HUFFMAN = 2;
		public static final int TIFF_PACKBITS = 32773;
	}
	/**
	 * <i>native declaration : otherlibs\highgui\grfmt_tiff.h:51</i><br>
	 * enum values
	 */
	public static interface TiffByteOrder {
		public static final int TIFF_ORDER_II = 18761;
		public static final int TIFF_ORDER_MM = 19789;
	}
	/**
	 * <i>native declaration : otherlibs\highgui\grfmt_tiff.h:58</i><br>
	 * enum values
	 */
	public static interface TiffTag {
		public static final int TIFF_TAG_WIDTH = 256;
		public static final int TIFF_TAG_HEIGHT = 257;
		public static final int TIFF_TAG_BITS_PER_SAMPLE = 258;
		public static final int TIFF_TAG_COMPRESSION = 259;
		public static final int TIFF_TAG_PHOTOMETRIC = 262;
		public static final int TIFF_TAG_STRIP_OFFSETS = 273;
		public static final int TIFF_TAG_STRIP_COUNTS = 279;
		public static final int TIFF_TAG_SAMPLES_PER_PIXEL = 277;
		public static final int TIFF_TAG_ROWS_PER_STRIP = 278;
		public static final int TIFF_TAG_PLANAR_CONFIG = 284;
		public static final int TIFF_TAG_COLOR_MAP = 320;
	}
	/**
	 * <i>native declaration : otherlibs\highgui\grfmt_tiff.h:74</i><br>
	 * enum values
	 */
	public static interface TiffFieldType {
		public static final int TIFF_TYPE_BYTE = 1;
		public static final int TIFF_TYPE_SHORT = 3;
		public static final int TIFF_TYPE_LONG = 4;
	}
	/// <i>native declaration : otherlibs\highgui\highgui.h</i>
	public static final int CV_CAP_FIREWIRE = 300;
	/// <i>native declaration : otherlibs\highgui\highgui.h</i>
	public static final int CV_CAP_PROP_GAIN = 14;
	/// <i>native declaration : otherlibs\highgui\highgui.h</i>
	public static final int CV_CAP_PROP_FORMAT = 8;
	/// <i>native declaration : otherlibs\highgui\highgui.h</i>
	public static final int CV_TYZX_RIGHT = 401;
	/// <i>native declaration : otherlibs\highgui\highgui.h</i>
	public static final int CV_CAP_STEREO = 400;
	/**
	 * define<br>
	 * SKIPPED:<br>
	 * <i>native declaration : otherlibs\highgui\\utils.h</i><br>
	 * icvCvt_BGR2RGB_16u_C3R
	 */
	/// <i>native declaration : otherlibs\highgui\highgui.h</i>
	public static final int CV_CAP_PROP_FRAME_HEIGHT = 4;
	/// <i>native declaration : otherlibs\highgui\highgui.h</i>
	public static final int CV_CAP_FIREWARE = 300;
	/// <i>native declaration : otherlibs\highgui\highgui.h</i>
	public static final int CV_EVENT_FLAG_CTRLKEY = 8;
	/**
	 * define<br>
	 * SKIPPED:<br>
	 * <i>native declaration : otherlibs\highgui\highgui.h</i><br>
	 * cvDestroyWindow
	 */
	/// <i>native declaration : otherlibs\highgui\highgui.h</i>
	public static final int CV_EVENT_MOUSEMOVE = 0;
	/// <i>native declaration : otherlibs\highgui\highgui.h</i>
	public static final int CV_CAP_PROP_POS_MSEC = 0;
	/// <i>native declaration : otherlibs\highgui\highgui.h</i>
	public static final int CV_EVENT_MBUTTONDOWN = 3;
	/// <i>native declaration : otherlibs\highgui\highgui.h</i>
	public static final int CV_CAP_DC1394 = 300;
	/// <i>native declaration : otherlibs\highgui\highgui.h</i>
	public static final int CV_EVENT_FLAG_RBUTTON = 2;
	/// <i>native declaration : otherlibs\highgui\_highgui.h</i>
	public static final int HG_NULLPTR = -4;
	/**
	 * define<br>
	 * SKIPPED:<br>
	 * <i>native declaration : otherlibs\highgui\highgui.h</i><br>
	 * cvShowImage
	 */
	/// <i>native declaration : otherlibs\highgui\highgui.h</i>
	public static final int CV_EVENT_RBUTTONDOWN = 2;
	/// <i>native declaration : otherlibs\highgui\_highgui.h</i>
	public static final int HG_OK = 0;
	/// <i>native declaration : otherlibs\highgui\highgui.h</i>
	public static final int CV_CAP_VFW = 200;
	/// <i>native declaration : otherlibs\highgui\highgui.h</i>
	public static final int CV_CAP_MIL = 100;
	/// <i>native declaration : otherlibs\highgui\highgui.h</i>
	public static final int CV_TYZX_Z = 403;
	/// <i>native declaration : otherlibs\highgui\highgui.h</i>
	public static final int CV_LOAD_IMAGE_GRAYSCALE = 0;
	/// <i>native declaration : otherlibs\highgui\highgui.h</i>
	public static final int CV_FOURCC_DEFAULT = -1;
	/// <i>native declaration : otherlibs\highgui\highgui.h</i>
	public static final int CV_CVTIMG_FLIP = 1;
	/// <i>native declaration : otherlibs\highgui\highgui.h</i>
	public static final int CV_EVENT_RBUTTONUP = 5;
	/// <i>native declaration : otherlibs\highgui\highgui.h</i>
	public static final int CV_CAP_PROP_HUE = 13;
	/**
	 * define<br>
	 * SKIPPED:<br>
	 * <i>native declaration : otherlibs\highgui\highgui.h</i><br>
	 * CvvImage
	 */
	/// <i>native declaration : otherlibs\highgui\highgui.h</i>
	public static final int CV_CAP_PROP_CONTRAST = 11;
	/// <i>native declaration : otherlibs\highgui\highgui.h</i>
	public static final int CV_CAP_IEEE1394 = 300;
	/// <i>native declaration : otherlibs\highgui\highgui.h</i>
	public static final int CV_CAP_V4L2 = 200;
	/// <i>native declaration : otherlibs\highgui\highgui.h</i>
	public static final int CV_CAP_PROP_FRAME_COUNT = 7;
	/// <i>native declaration : otherlibs\highgui\highgui.h</i>
	public static final int CV_CAP_ANY = 0;
	/// <i>native declaration : otherlibs\highgui\highgui.h</i>
	public static final int CV_EVENT_FLAG_ALTKEY = 32;
	/// <i>native declaration : otherlibs\highgui\highgui.h</i>
	public static final int CV_LOAD_IMAGE_ANYCOLOR = 4;
	/// <i>native declaration : otherlibs\highgui\bitstrm.h</i>
	public static final int RBS_THROW_FORB = -124;
	/**
	 * define<br>
	 * SKIPPED:<br>
	 * <i>native declaration : otherlibs\highgui\highgui.h</i><br>
	 * cvResizeWindow
	 */
	/**
	 * define<br>
	 * SKIPPED:<br>
	 * <i>native declaration : otherlibs\highgui\highgui.h</i><br>
	 * cvAddSearchPath
	 */
	/**
	 * define<br>
	 * SKIPPED:<br>
	 * <i>native declaration : otherlibs\highgui\\utils.h</i><br>
	 * icvCvt_BGR2RGB_8u_C3R
	 */
	/**
	 * define<br>
	 * SKIPPED:<br>
	 * <i>native declaration : otherlibs\highgui\highgui.h</i><br>
	 * cvInitSystem
	 */
	/**
	 * define<br>
	 * SKIPPED:<br>
	 * <i>native declaration : otherlibs\highgui\highgui.h</i><br>
	 * cvCreateTrackbar
	 */
	/// <i>native declaration : otherlibs\highgui\highgui.h</i>
	public static final int CV_LOAD_IMAGE_UNCHANGED = -1;
	/// <i>native declaration : otherlibs\highgui\highgui.h</i>
	public static final int CV_EVENT_MBUTTONUP = 6;
	/**
	 * define<br>
	 * SKIPPED:<br>
	 * <i>native declaration : otherlibs\highgui\\utils.h</i><br>
	 * icvCvt_BGRA2RGBA_8u_C4R
	 */
	/**
	 * define<br>
	 * SKIPPED:<br>
	 * <i>native declaration : otherlibs\highgui\highgui.h</i><br>
	 * cvCreateCameraCapture
	 */
	/// <i>native declaration : otherlibs\highgui\_highgui.h</i>
	public static final int HG_WCFAILED = -3;
	/// <i>native declaration : otherlibs\highgui\highgui.h</i>
	public static final int CV_EVENT_LBUTTONDBLCLK = 7;
	/// <i>native declaration : otherlibs\highgui\bitstrm.h</i>
	public static final int RBS_THROW_EOS = -123;
	/// <i>native declaration : otherlibs\highgui\highgui.h</i>
	public static final int CV_CAP_PROP_POS_FRAMES = 1;
	/// <i>native declaration : otherlibs\highgui\_highgui.h</i>
	public static final int HG_BADPARAM = -5;
	/// <i>native declaration : otherlibs\highgui\_highgui.h</i>
	public static final int HG_INITFAILED = -2;
	/**
	 * define<br>
	 * SKIPPED:<br>
	 * <i>native declaration : otherlibs\highgui\highgui.h</i><br>
	 * cvNamedWindow
	 */
	/// <i>native declaration : otherlibs\highgui\_highgui.h</i>
	public static final int HG_BADNAME = -1;
	/// <i>native declaration : otherlibs\highgui\highgui.h</i>
	public static final int CV_CAP_PROP_FRAME_WIDTH = 3;
	/// <i>native declaration : otherlibs\highgui\highgui.h</i>
	public static final int CV_EVENT_LBUTTONUP = 4;
	/**
	 * define<br>
	 * SKIPPED:<br>
	 * <i>native declaration : otherlibs\highgui\highgui.h</i><br>
	 * CV_WINDOW_AUTOSIZE
	 */
	/// <i>native declaration : otherlibs\highgui\highgui.h</i>
	public static final int CV_FOURCC_PROMPT = -1;
	/// <i>native declaration : otherlibs\highgui\highgui.h</i>
	public static final int CV_CAP_DSHOW = 700;
	/// <i>native declaration : otherlibs\highgui\highgui.h</i>
	public static final int CV_TYZX_LEFT = 400;
	/// <i>native declaration : otherlibs\highgui\highgui.h</i>
	public static final int CV_CAP_PROP_FPS = 5;
	/// <i>native declaration : otherlibs\highgui\highgui.h</i>
	public static final int CV_CAP_PROP_MODE = 9;
	/// <i>native declaration : otherlibs\highgui\highgui.h</i>
	public static final int CV_LOAD_IMAGE_ANYDEPTH = 2;
	/// <i>native declaration : otherlibs\highgui\highgui.h</i>
	public static final int CV_WINDOW_AUTOSIZE = 1;
	/// <i>native declaration : otherlibs\highgui\highgui.h</i>
	public static final int CV_CAP_PROP_POS_AVI_RATIO = 2;
	/// <i>native declaration : otherlibs\highgui\highgui.h</i>
	public static final int CV_CAP_PROP_CONVERT_RGB = 15;
	/// <i>native declaration : otherlibs\highgui\highgui.h</i>
	public static final int CV_EVENT_MBUTTONDBLCLK = 9;
	/// <i>native declaration : otherlibs\highgui\highgui.h</i>
	public static final int CV_CAP_PROP_FOURCC = 6;
	/// <i>native declaration : otherlibs\highgui\highgui.h</i>
	public static final int CV_CAP_TYZX = 400;
	/// <i>native declaration : otherlibs\highgui\highgui.h</i>
	public static final int CV_EVENT_RBUTTONDBLCLK = 8;
	/**
	 * define<br>
	 * SKIPPED:<br>
	 * <i>native declaration : otherlibs\highgui\highgui.h</i><br>
	 * cvSetPreprocessFuncWin32
	 */
	/// <i>native declaration : otherlibs\highgui\highgui.h</i>
	public static final int CV_CAP_CMU1394 = 300;
	/// <i>native declaration : otherlibs\highgui\bitstrm.h</i>
	public static final int RBS_HUFF_FORB = 2047;
	/// <i>native declaration : otherlibs\highgui\highgui.h</i>
	public static final int CV_CAP_PROP_SATURATION = 12;
	/// <i>native declaration : otherlibs\highgui\highgui.h</i>
	public static final int CV_EVENT_LBUTTONDOWN = 1;
	/**
	 * define<br>
	 * SKIPPED:<br>
	 * <i>native declaration : otherlibs\highgui\highgui.h</i><br>
	 * cvWriteFrame
	 */
	/**
	 * define<br>
	 * SKIPPED:<br>
	 * <i>native declaration : otherlibs\highgui\highgui.h</i><br>
	 * cvSetPostprocessFuncWin32
	 */
	/// <i>native declaration : otherlibs\highgui\_highgui.h</i>
	public static final int CV_TRACKBAR_MAGIC_VAL = 4325443;
	/**
	 * define<br>
	 * Conversion Error : (gst_app_sink_get_type())<br>
	 * SKIPPED:<br>
	 * <i>native declaration : otherlibs\highgui\gstappsink.h</i><br>
	 * (gst_app_sink_get_type())
	 */
	/// <i>native declaration : otherlibs\highgui\highgui.h</i>
	public static final int CV_CAP_V4L = 200;
	/**
	 * define<br>
	 * SKIPPED:<br>
	 * <i>native declaration : otherlibs\highgui\highgui.h</i><br>
	 * cvCreateFileCapture
	 */
	/**
	 * define<br>
	 * SKIPPED:<br>
	 * <i>native declaration : otherlibs\highgui\highgui.h</i><br>
	 * cvCreateVideoWriter
	 */
	/// <i>native declaration : otherlibs\highgui\highgui.h</i>
	public static final int CV_EVENT_FLAG_LBUTTON = 1;
	/**
	 * define<br>
	 * SKIPPED:<br>
	 * <i>native declaration : otherlibs\highgui\highgui.h</i><br>
	 * cvCaptureFromFile
	 */
	/// <i>native declaration : otherlibs\highgui\highgui.h</i>
	public static final int CV_CAP_UNICAP = 600;
	/// <i>native declaration : otherlibs\highgui\highgui.h</i>
	public static final int CV_CAP_PROP_BRIGHTNESS = 10;
	/// <i>native declaration : otherlibs\highgui\highgui.h</i>
	public static final int CV_LOAD_IMAGE_COLOR = 1;
	/// <i>native declaration : otherlibs\highgui\highgui.h</i>
	public static final int CV_CAP_QT = 500;
	/// <i>native declaration : otherlibs\highgui\highgui.h</i>
	public static final int CV_EVENT_FLAG_SHIFTKEY = 16;
	/**
	 * define<br>
	 * SKIPPED:<br>
	 * <i>native declaration : otherlibs\highgui\grfmt_base.h</i><br>
	 * goto
	 */
	/// <i>native declaration : otherlibs\highgui\_highgui.h</i>
	public static final int CV_WINDOW_MAGIC_VAL = 4325442;
	/**
	 * define<br>
	 * SKIPPED:<br>
	 * <i>native declaration : otherlibs\highgui\highgui.h</i><br>
	 * cvConvertImage
	 */
	/// <i>native declaration : otherlibs\highgui\grfmt_base.h</i>
	public static final int RBS_BAD_HEADER = -125;
	/// <i>native declaration : otherlibs\highgui\highgui.h</i>
	public static final int CV_CVTIMG_SWAP_RB = 2;
	/**
	 * define<br>
	 * SKIPPED:<br>
	 * <i>native declaration : otherlibs\highgui\highgui.h</i><br>
	 * cvSaveImage
	 */
	/// <i>native declaration : otherlibs\highgui\highgui.h</i>
	public static final int CV_TYZX_COLOR = 402;
	/// <i>native declaration : otherlibs\highgui\highgui.h</i>
	public static final int CV_EVENT_FLAG_MBUTTON = 4;
	/// <i>native declaration : otherlibs\highgui\highgui.h</i>
	public interface CvTrackbarCallback extends com.sun.jna.Callback {
		void invoke(int pos);
	}
	/// <i>native declaration : otherlibs\highgui\highgui.h</i>
	public interface CvMouseCallback extends com.sun.jna.Callback {
		void invoke(int event, int x, int y, int flags, com.sun.jna.Pointer param);
	}
	/**
	 * Original signature : <code>void icvCvt_BGR2Gray_16u_C3C1R(const ushort*, int, ushort*, int, CvSize, int)</code><br>
	 * <i>native declaration : otherlibs\highgui\\utils.h:58</i><br>
	 * @deprecated use the safer method {@link #icvCvt_BGR2Gray_16u_C3C1R(java.nio.ShortBuffer, int, java.nio.ShortBuffer, int, cxcore.CvSize.ByValue, int)} instead
	 */
	@com.ochafik.lang.jnaerator.runtime.Mangling({"_Z25icvCvt_BGR2Gray_16u_C3C1RPKjiPji6CvSizei", "?icvCvt_BGR2Gray_16u_C3C1R@@YAXPAIHPAIHUCvSize@@H@Z"})
	@java.lang.Deprecated
	void icvCvt_BGR2Gray_16u_C3C1R(com.sun.jna.ptr.ShortByReference bgr, int bgr_step, com.sun.jna.ptr.ShortByReference gray, int gray_step, cxcore.CvSize.ByValue size, int swap_rb);
	/**
	 * Original signature : <code>void icvCvt_BGR2Gray_16u_C3C1R(const ushort*, int, ushort*, int, CvSize, int)</code><br>
	 * <i>native declaration : otherlibs\highgui\\utils.h:58</i>
	 */
	@com.ochafik.lang.jnaerator.runtime.Mangling({"_Z25icvCvt_BGR2Gray_16u_C3C1RPKjiPji6CvSizei", "?icvCvt_BGR2Gray_16u_C3C1R@@YAXPAIHPAIHUCvSize@@H@Z"})
	void icvCvt_BGR2Gray_16u_C3C1R(java.nio.ShortBuffer bgr, int bgr_step, java.nio.ShortBuffer gray, int gray_step, cxcore.CvSize.ByValue size, int swap_rb);
	/**
	 * Original signature : <code>void icvCvt_BGR2Gray_8u_C3C1R(const uchar*, int, uchar*, int, CvSize, int)</code><br>
	 * <i>native declaration : otherlibs\highgui\\utils.h:61</i><br>
	 * @deprecated use the safer method {@link #icvCvt_BGR2Gray_8u_C3C1R(java.nio.ByteBuffer, int, java.nio.ByteBuffer, int, cxcore.CvSize.ByValue, int)} instead
	 */
	@com.ochafik.lang.jnaerator.runtime.Mangling({"_Z24icvCvt_BGR2Gray_8u_C3C1RPKhiPhi6CvSizei", "?icvCvt_BGR2Gray_8u_C3C1R@@YAXPAEHPAEHUCvSize@@H@Z"})
	@java.lang.Deprecated
	void icvCvt_BGR2Gray_8u_C3C1R(com.sun.jna.ptr.ByteByReference bgr, int bgr_step, com.sun.jna.ptr.ByteByReference gray, int gray_step, cxcore.CvSize.ByValue size, int swap_rb);
	/**
	 * Original signature : <code>void icvCvt_BGR2Gray_8u_C3C1R(const uchar*, int, uchar*, int, CvSize, int)</code><br>
	 * <i>native declaration : otherlibs\highgui\\utils.h:61</i>
	 */
	@com.ochafik.lang.jnaerator.runtime.Mangling({"_Z24icvCvt_BGR2Gray_8u_C3C1RPKhiPhi6CvSizei", "?icvCvt_BGR2Gray_8u_C3C1R@@YAXPAEHPAEHUCvSize@@H@Z"})
	void icvCvt_BGR2Gray_8u_C3C1R(java.nio.ByteBuffer bgr, int bgr_step, java.nio.ByteBuffer gray, int gray_step, cxcore.CvSize.ByValue size, int swap_rb);
	/**
	 * Original signature : <code>void icvCvt_BGRA2Gray_8u_C4C1R(const uchar*, int, uchar*, int, CvSize, int)</code><br>
	 * <i>native declaration : otherlibs\highgui\\utils.h:64</i><br>
	 * @deprecated use the safer method {@link #icvCvt_BGRA2Gray_8u_C4C1R(java.nio.ByteBuffer, int, java.nio.ByteBuffer, int, cxcore.CvSize.ByValue, int)} instead
	 */
	@com.ochafik.lang.jnaerator.runtime.Mangling({"_Z25icvCvt_BGRA2Gray_8u_C4C1RPKhiPhi6CvSizei", "?icvCvt_BGRA2Gray_8u_C4C1R@@YAXPAEHPAEHUCvSize@@H@Z"})
	@java.lang.Deprecated
	void icvCvt_BGRA2Gray_8u_C4C1R(com.sun.jna.ptr.ByteByReference bgra, int bgra_step, com.sun.jna.ptr.ByteByReference gray, int gray_step, cxcore.CvSize.ByValue size, int swap_rb);
	/**
	 * Original signature : <code>void icvCvt_BGRA2Gray_8u_C4C1R(const uchar*, int, uchar*, int, CvSize, int)</code><br>
	 * <i>native declaration : otherlibs\highgui\\utils.h:64</i>
	 */
	@com.ochafik.lang.jnaerator.runtime.Mangling({"_Z25icvCvt_BGRA2Gray_8u_C4C1RPKhiPhi6CvSizei", "?icvCvt_BGRA2Gray_8u_C4C1R@@YAXPAEHPAEHUCvSize@@H@Z"})
	void icvCvt_BGRA2Gray_8u_C4C1R(java.nio.ByteBuffer bgra, int bgra_step, java.nio.ByteBuffer gray, int gray_step, cxcore.CvSize.ByValue size, int swap_rb);
	/**
	 * Original signature : <code>void icvCvt_Gray2BGR_8u_C1C3R(const uchar*, int, uchar*, int, CvSize)</code><br>
	 * <i>native declaration : otherlibs\highgui\\utils.h:67</i><br>
	 * @deprecated use the safer method {@link #icvCvt_Gray2BGR_8u_C1C3R(java.nio.ByteBuffer, int, java.nio.ByteBuffer, int, cxcore.CvSize.ByValue)} instead
	 */
	@com.ochafik.lang.jnaerator.runtime.Mangling({"_Z24icvCvt_Gray2BGR_8u_C1C3RPKhiPhi6CvSize", "?icvCvt_Gray2BGR_8u_C1C3R@@YAXPAEHPAEHUCvSize@@@Z"})
	@java.lang.Deprecated
	void icvCvt_Gray2BGR_8u_C1C3R(com.sun.jna.ptr.ByteByReference gray, int gray_step, com.sun.jna.ptr.ByteByReference bgr, int bgr_step, cxcore.CvSize.ByValue size);
	/**
	 * Original signature : <code>void icvCvt_Gray2BGR_8u_C1C3R(const uchar*, int, uchar*, int, CvSize)</code><br>
	 * <i>native declaration : otherlibs\highgui\\utils.h:67</i>
	 */
	@com.ochafik.lang.jnaerator.runtime.Mangling({"_Z24icvCvt_Gray2BGR_8u_C1C3RPKhiPhi6CvSize", "?icvCvt_Gray2BGR_8u_C1C3R@@YAXPAEHPAEHUCvSize@@@Z"})
	void icvCvt_Gray2BGR_8u_C1C3R(java.nio.ByteBuffer gray, int gray_step, java.nio.ByteBuffer bgr, int bgr_step, cxcore.CvSize.ByValue size);
	/**
	 * Original signature : <code>void icvCvt_BGRA2BGR_8u_C4C3R(const uchar*, int, uchar*, int, CvSize, int)</code><br>
	 * <i>native declaration : otherlibs\highgui\\utils.h:69</i><br>
	 * @deprecated use the safer method {@link #icvCvt_BGRA2BGR_8u_C4C3R(java.nio.ByteBuffer, int, java.nio.ByteBuffer, int, cxcore.CvSize.ByValue, int)} instead
	 */
	@com.ochafik.lang.jnaerator.runtime.Mangling({"_Z24icvCvt_BGRA2BGR_8u_C4C3RPKhiPhi6CvSizei", "?icvCvt_BGRA2BGR_8u_C4C3R@@YAXPAEHPAEHUCvSize@@H@Z"})
	@java.lang.Deprecated
	void icvCvt_BGRA2BGR_8u_C4C3R(com.sun.jna.ptr.ByteByReference bgra, int bgra_step, com.sun.jna.ptr.ByteByReference bgr, int bgr_step, cxcore.CvSize.ByValue size, int swap_rb);
	/**
	 * Original signature : <code>void icvCvt_BGRA2BGR_8u_C4C3R(const uchar*, int, uchar*, int, CvSize, int)</code><br>
	 * <i>native declaration : otherlibs\highgui\\utils.h:69</i>
	 */
	@com.ochafik.lang.jnaerator.runtime.Mangling({"_Z24icvCvt_BGRA2BGR_8u_C4C3RPKhiPhi6CvSizei", "?icvCvt_BGRA2BGR_8u_C4C3R@@YAXPAEHPAEHUCvSize@@H@Z"})
	void icvCvt_BGRA2BGR_8u_C4C3R(java.nio.ByteBuffer bgra, int bgra_step, java.nio.ByteBuffer bgr, int bgr_step, cxcore.CvSize.ByValue size, int swap_rb);
	/**
	 * Original signature : <code>void icvCvt_BGR2RGB_8u_C3R(const uchar*, int, uchar*, int, CvSize)</code><br>
	 * <i>native declaration : otherlibs\highgui\\utils.h:72</i><br>
	 * @deprecated use the safer method {@link #icvCvt_BGR2RGB_8u_C3R(java.nio.ByteBuffer, int, java.nio.ByteBuffer, int, cxcore.CvSize.ByValue)} instead
	 */
	@com.ochafik.lang.jnaerator.runtime.Mangling({"_Z21icvCvt_BGR2RGB_8u_C3RPKhiPhi6CvSize", "?icvCvt_BGR2RGB_8u_C3R@@YAXPAEHPAEHUCvSize@@@Z"})
	@java.lang.Deprecated
	void icvCvt_BGR2RGB_8u_C3R(com.sun.jna.ptr.ByteByReference bgr, int bgr_step, com.sun.jna.ptr.ByteByReference rgb, int rgb_step, cxcore.CvSize.ByValue size);
	/**
	 * Original signature : <code>void icvCvt_BGR2RGB_8u_C3R(const uchar*, int, uchar*, int, CvSize)</code><br>
	 * <i>native declaration : otherlibs\highgui\\utils.h:72</i>
	 */
	@com.ochafik.lang.jnaerator.runtime.Mangling({"_Z21icvCvt_BGR2RGB_8u_C3RPKhiPhi6CvSize", "?icvCvt_BGR2RGB_8u_C3R@@YAXPAEHPAEHUCvSize@@@Z"})
	void icvCvt_BGR2RGB_8u_C3R(java.nio.ByteBuffer bgr, int bgr_step, java.nio.ByteBuffer rgb, int rgb_step, cxcore.CvSize.ByValue size);
	/**
	 * Original signature : <code>void icvCvt_BGR2RGB_16u_C3R(const ushort*, int, ushort*, int, CvSize)</code><br>
	 * <i>native declaration : otherlibs\highgui\\utils.h:75</i><br>
	 * @deprecated use the safer method {@link #icvCvt_BGR2RGB_16u_C3R(java.nio.ShortBuffer, int, java.nio.ShortBuffer, int, cxcore.CvSize.ByValue)} instead
	 */
	@com.ochafik.lang.jnaerator.runtime.Mangling({"_Z22icvCvt_BGR2RGB_16u_C3RPKjiPji6CvSize", "?icvCvt_BGR2RGB_16u_C3R@@YAXPAIHPAIHUCvSize@@@Z"})
	@java.lang.Deprecated
	void icvCvt_BGR2RGB_16u_C3R(com.sun.jna.ptr.ShortByReference bgr, int bgr_step, com.sun.jna.ptr.ShortByReference rgb, int rgb_step, cxcore.CvSize.ByValue size);
	/**
	 * Original signature : <code>void icvCvt_BGR2RGB_16u_C3R(const ushort*, int, ushort*, int, CvSize)</code><br>
	 * <i>native declaration : otherlibs\highgui\\utils.h:75</i>
	 */
	@com.ochafik.lang.jnaerator.runtime.Mangling({"_Z22icvCvt_BGR2RGB_16u_C3RPKjiPji6CvSize", "?icvCvt_BGR2RGB_16u_C3R@@YAXPAIHPAIHUCvSize@@@Z"})
	void icvCvt_BGR2RGB_16u_C3R(java.nio.ShortBuffer bgr, int bgr_step, java.nio.ShortBuffer rgb, int rgb_step, cxcore.CvSize.ByValue size);
	/**
	 * Original signature : <code>void icvCvt_BGRA2RGBA_8u_C4R(const uchar*, int, uchar*, int, CvSize)</code><br>
	 * <i>native declaration : otherlibs\highgui\\utils.h:79</i><br>
	 * @deprecated use the safer method {@link #icvCvt_BGRA2RGBA_8u_C4R(java.nio.ByteBuffer, int, java.nio.ByteBuffer, int, cxcore.CvSize.ByValue)} instead
	 */
	@com.ochafik.lang.jnaerator.runtime.Mangling({"_Z23icvCvt_BGRA2RGBA_8u_C4RPKhiPhi6CvSize", "?icvCvt_BGRA2RGBA_8u_C4R@@YAXPAEHPAEHUCvSize@@@Z"})
	@java.lang.Deprecated
	void icvCvt_BGRA2RGBA_8u_C4R(com.sun.jna.ptr.ByteByReference bgra, int bgra_step, com.sun.jna.ptr.ByteByReference rgba, int rgba_step, cxcore.CvSize.ByValue size);
	/**
	 * Original signature : <code>void icvCvt_BGRA2RGBA_8u_C4R(const uchar*, int, uchar*, int, CvSize)</code><br>
	 * <i>native declaration : otherlibs\highgui\\utils.h:79</i>
	 */
	@com.ochafik.lang.jnaerator.runtime.Mangling({"_Z23icvCvt_BGRA2RGBA_8u_C4RPKhiPhi6CvSize", "?icvCvt_BGRA2RGBA_8u_C4R@@YAXPAEHPAEHUCvSize@@@Z"})
	void icvCvt_BGRA2RGBA_8u_C4R(java.nio.ByteBuffer bgra, int bgra_step, java.nio.ByteBuffer rgba, int rgba_step, cxcore.CvSize.ByValue size);
	/**
	 * Original signature : <code>void icvCvt_BGR5552Gray_8u_C2C1R(const uchar*, int, uchar*, int, CvSize)</code><br>
	 * <i>native declaration : otherlibs\highgui\\utils.h:83</i><br>
	 * @deprecated use the safer method {@link #icvCvt_BGR5552Gray_8u_C2C1R(java.nio.ByteBuffer, int, java.nio.ByteBuffer, int, cxcore.CvSize.ByValue)} instead
	 */
	@com.ochafik.lang.jnaerator.runtime.Mangling({"_Z27icvCvt_BGR5552Gray_8u_C2C1RPKhiPhi6CvSize", "?icvCvt_BGR5552Gray_8u_C2C1R@@YAXPAEHPAEHUCvSize@@@Z"})
	@java.lang.Deprecated
	void icvCvt_BGR5552Gray_8u_C2C1R(com.sun.jna.ptr.ByteByReference bgr555, int bgr555_step, com.sun.jna.ptr.ByteByReference gray, int gray_step, cxcore.CvSize.ByValue size);
	/**
	 * Original signature : <code>void icvCvt_BGR5552Gray_8u_C2C1R(const uchar*, int, uchar*, int, CvSize)</code><br>
	 * <i>native declaration : otherlibs\highgui\\utils.h:83</i>
	 */
	@com.ochafik.lang.jnaerator.runtime.Mangling({"_Z27icvCvt_BGR5552Gray_8u_C2C1RPKhiPhi6CvSize", "?icvCvt_BGR5552Gray_8u_C2C1R@@YAXPAEHPAEHUCvSize@@@Z"})
	void icvCvt_BGR5552Gray_8u_C2C1R(java.nio.ByteBuffer bgr555, int bgr555_step, java.nio.ByteBuffer gray, int gray_step, cxcore.CvSize.ByValue size);
	/**
	 * Original signature : <code>void icvCvt_BGR5652Gray_8u_C2C1R(const uchar*, int, uchar*, int, CvSize)</code><br>
	 * <i>native declaration : otherlibs\highgui\\utils.h:85</i><br>
	 * @deprecated use the safer method {@link #icvCvt_BGR5652Gray_8u_C2C1R(java.nio.ByteBuffer, int, java.nio.ByteBuffer, int, cxcore.CvSize.ByValue)} instead
	 */
	@com.ochafik.lang.jnaerator.runtime.Mangling({"_Z27icvCvt_BGR5652Gray_8u_C2C1RPKhiPhi6CvSize", "?icvCvt_BGR5652Gray_8u_C2C1R@@YAXPAEHPAEHUCvSize@@@Z"})
	@java.lang.Deprecated
	void icvCvt_BGR5652Gray_8u_C2C1R(com.sun.jna.ptr.ByteByReference bgr565, int bgr565_step, com.sun.jna.ptr.ByteByReference gray, int gray_step, cxcore.CvSize.ByValue size);
	/**
	 * Original signature : <code>void icvCvt_BGR5652Gray_8u_C2C1R(const uchar*, int, uchar*, int, CvSize)</code><br>
	 * <i>native declaration : otherlibs\highgui\\utils.h:85</i>
	 */
	@com.ochafik.lang.jnaerator.runtime.Mangling({"_Z27icvCvt_BGR5652Gray_8u_C2C1RPKhiPhi6CvSize", "?icvCvt_BGR5652Gray_8u_C2C1R@@YAXPAEHPAEHUCvSize@@@Z"})
	void icvCvt_BGR5652Gray_8u_C2C1R(java.nio.ByteBuffer bgr565, int bgr565_step, java.nio.ByteBuffer gray, int gray_step, cxcore.CvSize.ByValue size);
	/**
	 * Original signature : <code>void icvCvt_BGR5552BGR_8u_C2C3R(const uchar*, int, uchar*, int, CvSize)</code><br>
	 * <i>native declaration : otherlibs\highgui\\utils.h:87</i><br>
	 * @deprecated use the safer method {@link #icvCvt_BGR5552BGR_8u_C2C3R(java.nio.ByteBuffer, int, java.nio.ByteBuffer, int, cxcore.CvSize.ByValue)} instead
	 */
	@com.ochafik.lang.jnaerator.runtime.Mangling({"_Z26icvCvt_BGR5552BGR_8u_C2C3RPKhiPhi6CvSize", "?icvCvt_BGR5552BGR_8u_C2C3R@@YAXPAEHPAEHUCvSize@@@Z"})
	@java.lang.Deprecated
	void icvCvt_BGR5552BGR_8u_C2C3R(com.sun.jna.ptr.ByteByReference bgr555, int bgr555_step, com.sun.jna.ptr.ByteByReference bgr, int bgr_step, cxcore.CvSize.ByValue size);
	/**
	 * Original signature : <code>void icvCvt_BGR5552BGR_8u_C2C3R(const uchar*, int, uchar*, int, CvSize)</code><br>
	 * <i>native declaration : otherlibs\highgui\\utils.h:87</i>
	 */
	@com.ochafik.lang.jnaerator.runtime.Mangling({"_Z26icvCvt_BGR5552BGR_8u_C2C3RPKhiPhi6CvSize", "?icvCvt_BGR5552BGR_8u_C2C3R@@YAXPAEHPAEHUCvSize@@@Z"})
	void icvCvt_BGR5552BGR_8u_C2C3R(java.nio.ByteBuffer bgr555, int bgr555_step, java.nio.ByteBuffer bgr, int bgr_step, cxcore.CvSize.ByValue size);
	/**
	 * Original signature : <code>void icvCvt_BGR5652BGR_8u_C2C3R(const uchar*, int, uchar*, int, CvSize)</code><br>
	 * <i>native declaration : otherlibs\highgui\\utils.h:89</i><br>
	 * @deprecated use the safer method {@link #icvCvt_BGR5652BGR_8u_C2C3R(java.nio.ByteBuffer, int, java.nio.ByteBuffer, int, cxcore.CvSize.ByValue)} instead
	 */
	@com.ochafik.lang.jnaerator.runtime.Mangling({"_Z26icvCvt_BGR5652BGR_8u_C2C3RPKhiPhi6CvSize", "?icvCvt_BGR5652BGR_8u_C2C3R@@YAXPAEHPAEHUCvSize@@@Z"})
	@java.lang.Deprecated
	void icvCvt_BGR5652BGR_8u_C2C3R(com.sun.jna.ptr.ByteByReference bgr565, int bgr565_step, com.sun.jna.ptr.ByteByReference bgr, int bgr_step, cxcore.CvSize.ByValue size);
	/**
	 * Original signature : <code>void icvCvt_BGR5652BGR_8u_C2C3R(const uchar*, int, uchar*, int, CvSize)</code><br>
	 * <i>native declaration : otherlibs\highgui\\utils.h:89</i>
	 */
	@com.ochafik.lang.jnaerator.runtime.Mangling({"_Z26icvCvt_BGR5652BGR_8u_C2C3RPKhiPhi6CvSize", "?icvCvt_BGR5652BGR_8u_C2C3R@@YAXPAEHPAEHUCvSize@@@Z"})
	void icvCvt_BGR5652BGR_8u_C2C3R(java.nio.ByteBuffer bgr565, int bgr565_step, java.nio.ByteBuffer bgr, int bgr_step, cxcore.CvSize.ByValue size);
	/**
	 * Original signature : <code>void icvCvt_CMYK2BGR_8u_C4C3R(const uchar*, int, uchar*, int, CvSize)</code><br>
	 * <i>native declaration : otherlibs\highgui\\utils.h:91</i><br>
	 * @deprecated use the safer method {@link #icvCvt_CMYK2BGR_8u_C4C3R(java.nio.ByteBuffer, int, java.nio.ByteBuffer, int, cxcore.CvSize.ByValue)} instead
	 */
	@com.ochafik.lang.jnaerator.runtime.Mangling({"_Z24icvCvt_CMYK2BGR_8u_C4C3RPKhiPhi6CvSize", "?icvCvt_CMYK2BGR_8u_C4C3R@@YAXPAEHPAEHUCvSize@@@Z"})
	@java.lang.Deprecated
	void icvCvt_CMYK2BGR_8u_C4C3R(com.sun.jna.ptr.ByteByReference cmyk, int cmyk_step, com.sun.jna.ptr.ByteByReference bgr, int bgr_step, cxcore.CvSize.ByValue size);
	/**
	 * Original signature : <code>void icvCvt_CMYK2BGR_8u_C4C3R(const uchar*, int, uchar*, int, CvSize)</code><br>
	 * <i>native declaration : otherlibs\highgui\\utils.h:91</i>
	 */
	@com.ochafik.lang.jnaerator.runtime.Mangling({"_Z24icvCvt_CMYK2BGR_8u_C4C3RPKhiPhi6CvSize", "?icvCvt_CMYK2BGR_8u_C4C3R@@YAXPAEHPAEHUCvSize@@@Z"})
	void icvCvt_CMYK2BGR_8u_C4C3R(java.nio.ByteBuffer cmyk, int cmyk_step, java.nio.ByteBuffer bgr, int bgr_step, cxcore.CvSize.ByValue size);
	/**
	 * Original signature : <code>void icvCvt_CMYK2Gray_8u_C4C1R(const uchar*, int, uchar*, int, CvSize)</code><br>
	 * <i>native declaration : otherlibs\highgui\\utils.h:93</i><br>
	 * @deprecated use the safer method {@link #icvCvt_CMYK2Gray_8u_C4C1R(java.nio.ByteBuffer, int, java.nio.ByteBuffer, int, cxcore.CvSize.ByValue)} instead
	 */
	@com.ochafik.lang.jnaerator.runtime.Mangling({"_Z25icvCvt_CMYK2Gray_8u_C4C1RPKhiPhi6CvSize", "?icvCvt_CMYK2Gray_8u_C4C1R@@YAXPAEHPAEHUCvSize@@@Z"})
	@java.lang.Deprecated
	void icvCvt_CMYK2Gray_8u_C4C1R(com.sun.jna.ptr.ByteByReference ycck, int ycck_step, com.sun.jna.ptr.ByteByReference gray, int gray_step, cxcore.CvSize.ByValue size);
	/**
	 * Original signature : <code>void icvCvt_CMYK2Gray_8u_C4C1R(const uchar*, int, uchar*, int, CvSize)</code><br>
	 * <i>native declaration : otherlibs\highgui\\utils.h:93</i>
	 */
	@com.ochafik.lang.jnaerator.runtime.Mangling({"_Z25icvCvt_CMYK2Gray_8u_C4C1RPKhiPhi6CvSize", "?icvCvt_CMYK2Gray_8u_C4C1R@@YAXPAEHPAEHUCvSize@@@Z"})
	void icvCvt_CMYK2Gray_8u_C4C1R(java.nio.ByteBuffer ycck, int ycck_step, java.nio.ByteBuffer gray, int gray_step, cxcore.CvSize.ByValue size);
	/**
	 * Original signature : <code>void FillGrayPalette(PaletteEntry*, int, bool)</code><br>
	 * <i>native declaration : otherlibs\highgui\\utils.h:96</i>
	 */
	@com.ochafik.lang.jnaerator.runtime.Mangling({"_Z15FillGrayPaletteP12PaletteEntryib", "?FillGrayPalette@@YAXPA12PaletteEntryH_N@Z"})
	void FillGrayPalette(highgui.PaletteEntry palette, int bpp, boolean negative);
	/**
	 * Original signature : <code>bool IsColorPalette(PaletteEntry*, int)</code><br>
	 * <i>native declaration : otherlibs\highgui\\utils.h:97</i>
	 */
	@com.ochafik.lang.jnaerator.runtime.Mangling({"_Z14IsColorPaletteP12PaletteEntryi", "?IsColorPalette@@YA_NPA12PaletteEntryH@Z"})
	boolean IsColorPalette(highgui.PaletteEntry palette, int bpp);
	/**
	 * Original signature : <code>void CvtPaletteToGray(const PaletteEntry*, uchar*, int)</code><br>
	 * <i>native declaration : otherlibs\highgui\\utils.h:98</i><br>
	 * @deprecated use the safer method {@link #CvtPaletteToGray(highgui.PaletteEntry, java.nio.ByteBuffer, int)} instead
	 */
	@com.ochafik.lang.jnaerator.runtime.Mangling({"_Z16CvtPaletteToGrayPK12PaletteEntryPhi", "?CvtPaletteToGray@@YAXPA12PaletteEntryPAEH@Z"})
	@java.lang.Deprecated
	void CvtPaletteToGray(highgui.PaletteEntry palette, com.sun.jna.ptr.ByteByReference grayPalette, int entries);
	/**
	 * Original signature : <code>void CvtPaletteToGray(const PaletteEntry*, uchar*, int)</code><br>
	 * <i>native declaration : otherlibs\highgui\\utils.h:98</i>
	 */
	@com.ochafik.lang.jnaerator.runtime.Mangling({"_Z16CvtPaletteToGrayPK12PaletteEntryPhi", "?CvtPaletteToGray@@YAXPA12PaletteEntryPAEH@Z"})
	void CvtPaletteToGray(highgui.PaletteEntry palette, java.nio.ByteBuffer grayPalette, int entries);
	/**
	 * Original signature : <code>uchar* FillUniColor(uchar*, uchar*&, int, int, int&, int, int, PaletteEntry)</code><br>
	 * <i>native declaration : otherlibs\highgui\\utils.h:99</i><br>
	 * @deprecated use the safer method {@link #FillUniColor(java.nio.ByteBuffer, com.sun.jna.ptr.PointerByReference, int, int, java.nio.IntBuffer, int, int, highgui.PaletteEntry.ByValue)} instead
	 */
	@com.ochafik.lang.jnaerator.runtime.Mangling({"_Z12FillUniColorPhRPhiiRiii12PaletteEntry", "?FillUniColor@@YAPAEPAEAAPAEHHAAHHH12PaletteEntry@Z"})
	@java.lang.Deprecated
	com.sun.jna.ptr.ByteByReference FillUniColor(com.sun.jna.ptr.ByteByReference data, com.sun.jna.ptr.PointerByReference line_end, int step, int width3, com.sun.jna.ptr.IntByReference y, int height, int count3, highgui.PaletteEntry.ByValue clr);
	/**
	 * Original signature : <code>uchar* FillUniColor(uchar*, uchar*&, int, int, int&, int, int, PaletteEntry)</code><br>
	 * <i>native declaration : otherlibs\highgui\\utils.h:99</i>
	 */
	@com.ochafik.lang.jnaerator.runtime.Mangling({"_Z12FillUniColorPhRPhiiRiii12PaletteEntry", "?FillUniColor@@YAPAEPAEAAPAEHHAAHHH12PaletteEntry@Z"})
	com.sun.jna.ptr.ByteByReference FillUniColor(java.nio.ByteBuffer data, com.sun.jna.ptr.PointerByReference line_end, int step, int width3, java.nio.IntBuffer y, int height, int count3, highgui.PaletteEntry.ByValue clr);
	/**
	 * Original signature : <code>uchar* FillUniGray(uchar*, uchar*&, int, int, int&, int, int, uchar)</code><br>
	 * <i>native declaration : otherlibs\highgui\\utils.h:101</i><br>
	 * @deprecated use the safer method {@link #FillUniGray(java.nio.ByteBuffer, com.sun.jna.ptr.PointerByReference, int, int, java.nio.IntBuffer, int, int, byte)} instead
	 */
	@com.ochafik.lang.jnaerator.runtime.Mangling({"_Z11FillUniGrayPhRPhiiRiiih", "?FillUniGray@@YAPAEPAEAAPAEHHAAHHHE@Z"})
	@java.lang.Deprecated
	com.sun.jna.ptr.ByteByReference FillUniGray(com.sun.jna.ptr.ByteByReference data, com.sun.jna.ptr.PointerByReference line_end, int step, int width3, com.sun.jna.ptr.IntByReference y, int height, int count3, byte clr);
	/**
	 * Original signature : <code>uchar* FillUniGray(uchar*, uchar*&, int, int, int&, int, int, uchar)</code><br>
	 * <i>native declaration : otherlibs\highgui\\utils.h:101</i>
	 */
	@com.ochafik.lang.jnaerator.runtime.Mangling({"_Z11FillUniGrayPhRPhiiRiiih", "?FillUniGray@@YAPAEPAEAAPAEHHAAHHHE@Z"})
	com.sun.jna.ptr.ByteByReference FillUniGray(java.nio.ByteBuffer data, com.sun.jna.ptr.PointerByReference line_end, int step, int width3, java.nio.IntBuffer y, int height, int count3, byte clr);
	/**
	 * Original signature : <code>uchar* FillColorRow8(uchar*, uchar*, int, PaletteEntry*)</code><br>
	 * <i>native declaration : otherlibs\highgui\\utils.h:104</i><br>
	 * @deprecated use the safer method {@link #FillColorRow8(java.nio.ByteBuffer, java.nio.ByteBuffer, int, highgui.PaletteEntry)} instead
	 */
	@com.ochafik.lang.jnaerator.runtime.Mangling({"_Z13FillColorRow8PhPhiP12PaletteEntry", "?FillColorRow8@@YAPAEPAEPAEHPA12PaletteEntry@Z"})
	@java.lang.Deprecated
	com.sun.jna.ptr.ByteByReference FillColorRow8(com.sun.jna.ptr.ByteByReference data, com.sun.jna.ptr.ByteByReference indices, int len, highgui.PaletteEntry palette);
	/**
	 * Original signature : <code>uchar* FillColorRow8(uchar*, uchar*, int, PaletteEntry*)</code><br>
	 * <i>native declaration : otherlibs\highgui\\utils.h:104</i>
	 */
	@com.ochafik.lang.jnaerator.runtime.Mangling({"_Z13FillColorRow8PhPhiP12PaletteEntry", "?FillColorRow8@@YAPAEPAEPAEHPA12PaletteEntry@Z"})
	com.sun.jna.ptr.ByteByReference FillColorRow8(java.nio.ByteBuffer data, java.nio.ByteBuffer indices, int len, highgui.PaletteEntry palette);
	/**
	 * Original signature : <code>uchar* FillGrayRow8(uchar*, uchar*, int, uchar*)</code><br>
	 * <i>native declaration : otherlibs\highgui\\utils.h:105</i><br>
	 * @deprecated use the safer method {@link #FillGrayRow8(java.nio.ByteBuffer, java.nio.ByteBuffer, int, java.nio.ByteBuffer)} instead
	 */
	@com.ochafik.lang.jnaerator.runtime.Mangling({"_Z12FillGrayRow8PhPhiPh", "?FillGrayRow8@@YAPAEPAEPAEHPAE@Z"})
	@java.lang.Deprecated
	com.sun.jna.ptr.ByteByReference FillGrayRow8(com.sun.jna.ptr.ByteByReference data, com.sun.jna.ptr.ByteByReference indices, int len, com.sun.jna.ptr.ByteByReference palette);
	/**
	 * Original signature : <code>uchar* FillGrayRow8(uchar*, uchar*, int, uchar*)</code><br>
	 * <i>native declaration : otherlibs\highgui\\utils.h:105</i>
	 */
	@com.ochafik.lang.jnaerator.runtime.Mangling({"_Z12FillGrayRow8PhPhiPh", "?FillGrayRow8@@YAPAEPAEPAEHPAE@Z"})
	com.sun.jna.ptr.ByteByReference FillGrayRow8(java.nio.ByteBuffer data, java.nio.ByteBuffer indices, int len, java.nio.ByteBuffer palette);
	/**
	 * Original signature : <code>uchar* FillColorRow4(uchar*, uchar*, int, PaletteEntry*)</code><br>
	 * <i>native declaration : otherlibs\highgui\\utils.h:106</i><br>
	 * @deprecated use the safer method {@link #FillColorRow4(java.nio.ByteBuffer, java.nio.ByteBuffer, int, highgui.PaletteEntry)} instead
	 */
	@com.ochafik.lang.jnaerator.runtime.Mangling({"_Z13FillColorRow4PhPhiP12PaletteEntry", "?FillColorRow4@@YAPAEPAEPAEHPA12PaletteEntry@Z"})
	@java.lang.Deprecated
	com.sun.jna.ptr.ByteByReference FillColorRow4(com.sun.jna.ptr.ByteByReference data, com.sun.jna.ptr.ByteByReference indices, int len, highgui.PaletteEntry palette);
	/**
	 * Original signature : <code>uchar* FillColorRow4(uchar*, uchar*, int, PaletteEntry*)</code><br>
	 * <i>native declaration : otherlibs\highgui\\utils.h:106</i>
	 */
	@com.ochafik.lang.jnaerator.runtime.Mangling({"_Z13FillColorRow4PhPhiP12PaletteEntry", "?FillColorRow4@@YAPAEPAEPAEHPA12PaletteEntry@Z"})
	com.sun.jna.ptr.ByteByReference FillColorRow4(java.nio.ByteBuffer data, java.nio.ByteBuffer indices, int len, highgui.PaletteEntry palette);
	/**
	 * Original signature : <code>uchar* FillGrayRow4(uchar*, uchar*, int, uchar*)</code><br>
	 * <i>native declaration : otherlibs\highgui\\utils.h:107</i><br>
	 * @deprecated use the safer method {@link #FillGrayRow4(java.nio.ByteBuffer, java.nio.ByteBuffer, int, java.nio.ByteBuffer)} instead
	 */
	@com.ochafik.lang.jnaerator.runtime.Mangling({"_Z12FillGrayRow4PhPhiPh", "?FillGrayRow4@@YAPAEPAEPAEHPAE@Z"})
	@java.lang.Deprecated
	com.sun.jna.ptr.ByteByReference FillGrayRow4(com.sun.jna.ptr.ByteByReference data, com.sun.jna.ptr.ByteByReference indices, int len, com.sun.jna.ptr.ByteByReference palette);
	/**
	 * Original signature : <code>uchar* FillGrayRow4(uchar*, uchar*, int, uchar*)</code><br>
	 * <i>native declaration : otherlibs\highgui\\utils.h:107</i>
	 */
	@com.ochafik.lang.jnaerator.runtime.Mangling({"_Z12FillGrayRow4PhPhiPh", "?FillGrayRow4@@YAPAEPAEPAEHPAE@Z"})
	com.sun.jna.ptr.ByteByReference FillGrayRow4(java.nio.ByteBuffer data, java.nio.ByteBuffer indices, int len, java.nio.ByteBuffer palette);
	/**
	 * Original signature : <code>uchar* FillColorRow1(uchar*, uchar*, int, PaletteEntry*)</code><br>
	 * <i>native declaration : otherlibs\highgui\\utils.h:108</i><br>
	 * @deprecated use the safer method {@link #FillColorRow1(java.nio.ByteBuffer, java.nio.ByteBuffer, int, highgui.PaletteEntry)} instead
	 */
	@com.ochafik.lang.jnaerator.runtime.Mangling({"_Z13FillColorRow1PhPhiP12PaletteEntry", "?FillColorRow1@@YAPAEPAEPAEHPA12PaletteEntry@Z"})
	@java.lang.Deprecated
	com.sun.jna.ptr.ByteByReference FillColorRow1(com.sun.jna.ptr.ByteByReference data, com.sun.jna.ptr.ByteByReference indices, int len, highgui.PaletteEntry palette);
	/**
	 * Original signature : <code>uchar* FillColorRow1(uchar*, uchar*, int, PaletteEntry*)</code><br>
	 * <i>native declaration : otherlibs\highgui\\utils.h:108</i>
	 */
	@com.ochafik.lang.jnaerator.runtime.Mangling({"_Z13FillColorRow1PhPhiP12PaletteEntry", "?FillColorRow1@@YAPAEPAEPAEHPA12PaletteEntry@Z"})
	com.sun.jna.ptr.ByteByReference FillColorRow1(java.nio.ByteBuffer data, java.nio.ByteBuffer indices, int len, highgui.PaletteEntry palette);
	/**
	 * Original signature : <code>uchar* FillGrayRow1(uchar*, uchar*, int, uchar*)</code><br>
	 * <i>native declaration : otherlibs\highgui\\utils.h:109</i><br>
	 * @deprecated use the safer method {@link #FillGrayRow1(java.nio.ByteBuffer, java.nio.ByteBuffer, int, java.nio.ByteBuffer)} instead
	 */
	@com.ochafik.lang.jnaerator.runtime.Mangling({"_Z12FillGrayRow1PhPhiPh", "?FillGrayRow1@@YAPAEPAEPAEHPAE@Z"})
	@java.lang.Deprecated
	com.sun.jna.ptr.ByteByReference FillGrayRow1(com.sun.jna.ptr.ByteByReference data, com.sun.jna.ptr.ByteByReference indices, int len, com.sun.jna.ptr.ByteByReference palette);
	/**
	 * Original signature : <code>uchar* FillGrayRow1(uchar*, uchar*, int, uchar*)</code><br>
	 * <i>native declaration : otherlibs\highgui\\utils.h:109</i>
	 */
	@com.ochafik.lang.jnaerator.runtime.Mangling({"_Z12FillGrayRow1PhPhiPh", "?FillGrayRow1@@YAPAEPAEPAEHPAE@Z"})
	com.sun.jna.ptr.ByteByReference FillGrayRow1(java.nio.ByteBuffer data, java.nio.ByteBuffer indices, int len, java.nio.ByteBuffer palette);
	/**
	 * Original signature : <code>cvHaveImageReader(const char*)</code><br>
	 * <i>native declaration : otherlibs\highgui\_highgui.h:88</i><br>
	 * @deprecated use the safer method {@link #cvHaveImageReader(java.lang.String)} instead
	 */
	@com.ochafik.lang.jnaerator.runtime.Mangling({"_Z17cvHaveImageReaderPKc", "?cvHaveImageReader@@YAXPAD@Z"})
	@java.lang.Deprecated
	int cvHaveImageReader(com.sun.jna.ptr.ByteByReference filename);
	/**
	 * Original signature : <code>cvHaveImageReader(const char*)</code><br>
	 * <i>native declaration : otherlibs\highgui\_highgui.h:88</i>
	 */
	@com.ochafik.lang.jnaerator.runtime.Mangling({"_Z17cvHaveImageReaderPKc", "?cvHaveImageReader@@YAXPAD@Z"})
	int cvHaveImageReader(java.lang.String filename);
	/**
	 * Original signature : <code>cvHaveImageWriter(const char*)</code><br>
	 * <i>native declaration : otherlibs\highgui\_highgui.h:89</i><br>
	 * @deprecated use the safer method {@link #cvHaveImageWriter(java.lang.String)} instead
	 */
	@com.ochafik.lang.jnaerator.runtime.Mangling({"_Z17cvHaveImageWriterPKc", "?cvHaveImageWriter@@YAXPAD@Z"})
	@java.lang.Deprecated
	int cvHaveImageWriter(com.sun.jna.ptr.ByteByReference filename);
	/**
	 * Original signature : <code>cvHaveImageWriter(const char*)</code><br>
	 * <i>native declaration : otherlibs\highgui\_highgui.h:89</i>
	 */
	@com.ochafik.lang.jnaerator.runtime.Mangling({"_Z17cvHaveImageWriterPKc", "?cvHaveImageWriter@@YAXPAD@Z"})
	int cvHaveImageWriter(java.lang.String filename);
	/**
	 * Original signature : <code>CvCapture* cvCreateFileCapture_Images(const char*)</code><br>
	 * <i>native declaration : otherlibs\highgui\_highgui.h:91</i><br>
	 * @deprecated use the safer method {@link #cvCreateFileCapture_Images(java.lang.String)} instead
	 */
	@com.ochafik.lang.jnaerator.runtime.Mangling({"_Z26cvCreateFileCapture_ImagesPKc", "?cvCreateFileCapture_Images@@YAPA9CvCapturePAD@Z"})
	@java.lang.Deprecated
	highgui.CvCapture cvCreateFileCapture_Images(com.sun.jna.ptr.ByteByReference filename);
	/**
	 * Original signature : <code>CvCapture* cvCreateFileCapture_Images(const char*)</code><br>
	 * <i>native declaration : otherlibs\highgui\_highgui.h:91</i>
	 */
	@com.ochafik.lang.jnaerator.runtime.Mangling({"_Z26cvCreateFileCapture_ImagesPKc", "?cvCreateFileCapture_Images@@YAPA9CvCapturePAD@Z"})
	highgui.CvCapture cvCreateFileCapture_Images(java.lang.String filename);
	/**
	 * Original signature : <code>CvVideoWriter* cvCreateVideoWriter_Images(const char*)</code><br>
	 * <i>native declaration : otherlibs\highgui\_highgui.h:92</i><br>
	 * @deprecated use the safer method {@link #cvCreateVideoWriter_Images(java.lang.String)} instead
	 */
	@com.ochafik.lang.jnaerator.runtime.Mangling({"_Z26cvCreateVideoWriter_ImagesPKc", "?cvCreateVideoWriter_Images@@YAPA13CvVideoWriterPAD@Z"})
	@java.lang.Deprecated
	highgui.CvVideoWriter cvCreateVideoWriter_Images(com.sun.jna.ptr.ByteByReference filename);
	/**
	 * Original signature : <code>CvVideoWriter* cvCreateVideoWriter_Images(const char*)</code><br>
	 * <i>native declaration : otherlibs\highgui\_highgui.h:92</i>
	 */
	@com.ochafik.lang.jnaerator.runtime.Mangling({"_Z26cvCreateVideoWriter_ImagesPKc", "?cvCreateVideoWriter_Images@@YAPA13CvVideoWriterPAD@Z"})
	highgui.CvVideoWriter cvCreateVideoWriter_Images(java.lang.String filename);
	/**
	 * this function is used to set some external parameters in case of X Window<br>
	 * Original signature : <code>int cvInitSystem(int, char**)</code><br>
	 * <i>native declaration : otherlibs\highgui\highgui.h:110</i>
	 */
	int cvInitSystem(int argc, com.sun.jna.ptr.PointerByReference argv);
	/**
	 * Original signature : <code>int cvStartWindowThread()</code><br>
	 * <i>native declaration : otherlibs\highgui\highgui.h:112</i>
	 */
	int cvStartWindowThread();
	/**
	 * create window<br>
	 * Original signature : <code>int cvNamedWindow(const char*, int)</code><br>
	 * <i>native declaration : otherlibs\highgui\highgui.h:116</i><br>
	 * @deprecated use the safer method {@link #cvNamedWindow(java.lang.String, int)} instead
	 */
	@java.lang.Deprecated
	int cvNamedWindow(com.sun.jna.ptr.ByteByReference name, int flags);
	/**
	 * create window<br>
	 * Original signature : <code>int cvNamedWindow(const char*, int)</code><br>
	 * <i>native declaration : otherlibs\highgui\highgui.h:116</i>
	 */
	int cvNamedWindow(java.lang.String name, int flags);
	/**
	 * display image within window (highgui windows remember their content)<br>
	 * Original signature : <code>void cvShowImage(const char*, const CvArr*)</code><br>
	 * <i>native declaration : otherlibs\highgui\highgui.h:119</i><br>
	 * @deprecated use the safer method {@link #cvShowImage(java.lang.String, highgui.HighguiLibrary.CvArr)} instead
	 */
	@java.lang.Deprecated
	void cvShowImage(com.sun.jna.ptr.ByteByReference name, highgui.HighguiLibrary.CvArr image);
	/**
	 * display image within window (highgui windows remember their content)<br>
	 * Original signature : <code>void cvShowImage(const char*, const CvArr*)</code><br>
	 * <i>native declaration : otherlibs\highgui\highgui.h:119</i>
	 */
	void cvShowImage(java.lang.String name, highgui.HighguiLibrary.CvArr image);
	/**
	 * resize/move window<br>
	 * Original signature : <code>void cvResizeWindow(const char*, int, int)</code><br>
	 * <i>native declaration : otherlibs\highgui\highgui.h:122</i><br>
	 * @deprecated use the safer method {@link #cvResizeWindow(java.lang.String, int, int)} instead
	 */
	@java.lang.Deprecated
	void cvResizeWindow(com.sun.jna.ptr.ByteByReference name, int width, int height);
	/**
	 * resize/move window<br>
	 * Original signature : <code>void cvResizeWindow(const char*, int, int)</code><br>
	 * <i>native declaration : otherlibs\highgui\highgui.h:122</i>
	 */
	void cvResizeWindow(java.lang.String name, int width, int height);
	/**
	 * Original signature : <code>void cvMoveWindow(const char*, int, int)</code><br>
	 * <i>native declaration : otherlibs\highgui\highgui.h:123</i><br>
	 * @deprecated use the safer method {@link #cvMoveWindow(java.lang.String, int, int)} instead
	 */
	@java.lang.Deprecated
	void cvMoveWindow(com.sun.jna.ptr.ByteByReference name, int x, int y);
	/**
	 * Original signature : <code>void cvMoveWindow(const char*, int, int)</code><br>
	 * <i>native declaration : otherlibs\highgui\highgui.h:123</i>
	 */
	void cvMoveWindow(java.lang.String name, int x, int y);
	/**
	 * destroy window and all the trackers associated with it<br>
	 * Original signature : <code>void cvDestroyWindow(const char*)</code><br>
	 * <i>native declaration : otherlibs\highgui\highgui.h:127</i><br>
	 * @deprecated use the safer method {@link #cvDestroyWindow(java.lang.String)} instead
	 */
	@java.lang.Deprecated
	void cvDestroyWindow(com.sun.jna.ptr.ByteByReference name);
	/**
	 * destroy window and all the trackers associated with it<br>
	 * Original signature : <code>void cvDestroyWindow(const char*)</code><br>
	 * <i>native declaration : otherlibs\highgui\highgui.h:127</i>
	 */
	void cvDestroyWindow(java.lang.String name);
	/**
	 * Original signature : <code>void cvDestroyAllWindows()</code><br>
	 * <i>native declaration : otherlibs\highgui\highgui.h:129</i>
	 */
	void cvDestroyAllWindows();
	/**
	 * get native window handle (HWND in case of Win32 and Widget in case of X Window)<br>
	 * Original signature : <code>void* cvGetWindowHandle(const char*)</code><br>
	 * <i>native declaration : otherlibs\highgui\highgui.h:132</i><br>
	 * @deprecated use the safer method {@link #cvGetWindowHandle(java.lang.String)} instead
	 */
	@java.lang.Deprecated
	com.sun.jna.Pointer cvGetWindowHandle(com.sun.jna.ptr.ByteByReference name);
	/**
	 * get native window handle (HWND in case of Win32 and Widget in case of X Window)<br>
	 * Original signature : <code>void* cvGetWindowHandle(const char*)</code><br>
	 * <i>native declaration : otherlibs\highgui\highgui.h:132</i>
	 */
	com.sun.jna.Pointer cvGetWindowHandle(java.lang.String name);
	/**
	 * get name of highgui window given its native handle<br>
	 * Original signature : <code>char* cvGetWindowName(void*)</code><br>
	 * <i>native declaration : otherlibs\highgui\highgui.h:135</i>
	 */
	com.sun.jna.ptr.ByteByReference cvGetWindowName(com.sun.jna.Pointer window_handle);
	/**
	 * create trackbar and display it on top of given window, set callback<br>
	 * Original signature : <code>int cvCreateTrackbar(const char*, const char*, int*, int, CvTrackbarCallback)</code><br>
	 * <i>native declaration : otherlibs\highgui\highgui.h:141</i><br>
	 * @deprecated use the safer method {@link #cvCreateTrackbar(java.lang.String, java.lang.String, java.nio.IntBuffer, int, highgui.HighguiLibrary.CvTrackbarCallback)} instead
	 */
	@java.lang.Deprecated
	int cvCreateTrackbar(com.sun.jna.ptr.ByteByReference trackbar_name, com.sun.jna.ptr.ByteByReference window_name, com.sun.jna.ptr.IntByReference value, int count, highgui.HighguiLibrary.CvTrackbarCallback on_change);
	/**
	 * create trackbar and display it on top of given window, set callback<br>
	 * Original signature : <code>int cvCreateTrackbar(const char*, const char*, int*, int, CvTrackbarCallback)</code><br>
	 * <i>native declaration : otherlibs\highgui\highgui.h:141</i>
	 */
	int cvCreateTrackbar(java.lang.String trackbar_name, java.lang.String window_name, java.nio.IntBuffer value, int count, highgui.HighguiLibrary.CvTrackbarCallback on_change);
	/**
	 * retrieve or set trackbar position<br>
	 * Original signature : <code>int cvGetTrackbarPos(const char*, const char*)</code><br>
	 * <i>native declaration : otherlibs\highgui\highgui.h:145</i><br>
	 * @deprecated use the safer method {@link #cvGetTrackbarPos(java.lang.String, java.lang.String)} instead
	 */
	@java.lang.Deprecated
	int cvGetTrackbarPos(com.sun.jna.ptr.ByteByReference trackbar_name, com.sun.jna.ptr.ByteByReference window_name);
	/**
	 * retrieve or set trackbar position<br>
	 * Original signature : <code>int cvGetTrackbarPos(const char*, const char*)</code><br>
	 * <i>native declaration : otherlibs\highgui\highgui.h:145</i>
	 */
	int cvGetTrackbarPos(java.lang.String trackbar_name, java.lang.String window_name);
	/**
	 * Original signature : <code>void cvSetTrackbarPos(const char*, const char*, int)</code><br>
	 * <i>native declaration : otherlibs\highgui\highgui.h:146</i><br>
	 * @deprecated use the safer method {@link #cvSetTrackbarPos(java.lang.String, java.lang.String, int)} instead
	 */
	@java.lang.Deprecated
	void cvSetTrackbarPos(com.sun.jna.ptr.ByteByReference trackbar_name, com.sun.jna.ptr.ByteByReference window_name, int pos);
	/**
	 * Original signature : <code>void cvSetTrackbarPos(const char*, const char*, int)</code><br>
	 * <i>native declaration : otherlibs\highgui\highgui.h:146</i>
	 */
	void cvSetTrackbarPos(java.lang.String trackbar_name, java.lang.String window_name, int pos);
	/**
	 * assign callback for mouse events<br>
	 * Original signature : <code>void cvSetMouseCallback(const char*, CvMouseCallback, void*)</code><br>
	 * <i>native declaration : otherlibs\highgui\highgui.h:169</i><br>
	 * @deprecated use the safer method {@link #cvSetMouseCallback(java.lang.String, highgui.HighguiLibrary.CvMouseCallback, com.sun.jna.Pointer)} instead
	 */
	@java.lang.Deprecated
	void cvSetMouseCallback(com.sun.jna.ptr.ByteByReference window_name, highgui.HighguiLibrary.CvMouseCallback on_mouse, com.sun.jna.Pointer param);
	/**
	 * assign callback for mouse events<br>
	 * Original signature : <code>void cvSetMouseCallback(const char*, CvMouseCallback, void*)</code><br>
	 * <i>native declaration : otherlibs\highgui\highgui.h:169</i>
	 */
	void cvSetMouseCallback(java.lang.String window_name, highgui.HighguiLibrary.CvMouseCallback on_mouse, com.sun.jna.Pointer param);
	/**
	 * load image from file<br>
	 * iscolor can be a combination of above flags where CV_LOAD_IMAGE_UNCHANGED<br>
	 * overrides the other flags<br>
	 * using CV_LOAD_IMAGE_ANYCOLOR alone is equivalent to CV_LOAD_IMAGE_UNCHANGED<br>
	 * unless CV_LOAD_IMAGE_ANYDEPTH is specified images are converted to 8bit<br>
	 * Original signature : <code>IplImage* cvLoadImage(const char*, int)</code><br>
	 * <i>native declaration : otherlibs\highgui\highgui.h:189</i><br>
	 * @deprecated use the safer method {@link #cvLoadImage(java.lang.String, int)} instead
	 */
	@java.lang.Deprecated
	cxcore.IplImage cvLoadImage(com.sun.jna.ptr.ByteByReference filename, int iscolor);
	/**
	 * load image from file<br>
	 * iscolor can be a combination of above flags where CV_LOAD_IMAGE_UNCHANGED<br>
	 * overrides the other flags<br>
	 * using CV_LOAD_IMAGE_ANYCOLOR alone is equivalent to CV_LOAD_IMAGE_UNCHANGED<br>
	 * unless CV_LOAD_IMAGE_ANYDEPTH is specified images are converted to 8bit<br>
	 * Original signature : <code>IplImage* cvLoadImage(const char*, int)</code><br>
	 * <i>native declaration : otherlibs\highgui\highgui.h:189</i>
	 */
	cxcore.IplImage cvLoadImage(java.lang.String filename, int iscolor);
	/**
	 * Original signature : <code>CvMat* cvLoadImageM(const char*, int)</code><br>
	 * <i>native declaration : otherlibs\highgui\highgui.h:190</i><br>
	 * @deprecated use the safer method {@link #cvLoadImageM(java.lang.String, int)} instead
	 */
	@java.lang.Deprecated
	cxcore.CvMat cvLoadImageM(com.sun.jna.ptr.ByteByReference filename, int iscolor);
	/**
	 * Original signature : <code>CvMat* cvLoadImageM(const char*, int)</code><br>
	 * <i>native declaration : otherlibs\highgui\highgui.h:190</i>
	 */
	cxcore.CvMat cvLoadImageM(java.lang.String filename, int iscolor);
	/**
	 * save image to file<br>
	 * Original signature : <code>int cvSaveImage(const char*, const CvArr*)</code><br>
	 * <i>native declaration : otherlibs\highgui\highgui.h:193</i><br>
	 * @deprecated use the safer method {@link #cvSaveImage(java.lang.String, highgui.HighguiLibrary.CvArr)} instead
	 */
	@java.lang.Deprecated
	int cvSaveImage(com.sun.jna.ptr.ByteByReference filename, highgui.HighguiLibrary.CvArr image);
	/**
	 * save image to file<br>
	 * Original signature : <code>int cvSaveImage(const char*, const CvArr*)</code><br>
	 * <i>native declaration : otherlibs\highgui\highgui.h:193</i>
	 */
	int cvSaveImage(java.lang.String filename, highgui.HighguiLibrary.CvArr image);
	/**
	 * utility function: convert one image to another with optional vertical flip<br>
	 * Original signature : <code>void cvConvertImage(const CvArr*, CvArr*, int)</code><br>
	 * <i>native declaration : otherlibs\highgui\highgui.h:198</i>
	 */
	void cvConvertImage(highgui.HighguiLibrary.CvArr src, highgui.HighguiLibrary.CvArr dst, int flags);
	/**
	 * wait for key event infinitely (delay<=0) or for "delay" milliseconds<br>
	 * Original signature : <code>int cvWaitKey(int)</code><br>
	 * <i>native declaration : otherlibs\highgui\highgui.h:201</i>
	 */
	int cvWaitKey(int delay);
	/**
	 * start capturing frames from video file<br>
	 * Original signature : <code>CvCapture* cvCreateFileCapture(const char*)</code><br>
	 * <i>native declaration : otherlibs\highgui\highgui.h:212</i><br>
	 * @deprecated use the safer method {@link #cvCreateFileCapture(java.lang.String)} instead
	 */
	@java.lang.Deprecated
	highgui.CvCapture cvCreateFileCapture(com.sun.jna.ptr.ByteByReference filename);
	/**
	 * start capturing frames from video file<br>
	 * Original signature : <code>CvCapture* cvCreateFileCapture(const char*)</code><br>
	 * <i>native declaration : otherlibs\highgui\highgui.h:212</i>
	 */
	highgui.CvCapture cvCreateFileCapture(java.lang.String filename);
	/**
	 * start capturing frames from camera: index = camera_index + domain_offset (CV_CAP_*)<br>
	 * Original signature : <code>CvCapture* cvCreateCameraCapture(int)</code><br>
	 * <i>native declaration : otherlibs\highgui\highgui.h:242</i>
	 */
	highgui.CvCapture cvCreateCameraCapture(int index);
	/**
	 * grab a frame, return 1 on success, 0 on fail.<br>
	 * this function is thought to be fast<br>
	 * Original signature : <code>int cvGrabFrame(CvCapture*)</code><br>
	 * <i>native declaration : otherlibs\highgui\highgui.h:246</i>
	 */
	int cvGrabFrame(highgui.CvCapture capture);
	/**
	 * get the frame grabbed with cvGrabFrame(..)<br>
	 * This function may apply some frame processing like<br>
	 * frame decompression, flipping etc.<br>
	 * !!!DO NOT RELEASE or MODIFY the retrieved frame!!!<br>
	 * Original signature : <code>IplImage* cvRetrieveFrame(CvCapture*)</code><br>
	 * <i>native declaration : otherlibs\highgui\highgui.h:252</i>
	 */
	cxcore.IplImage cvRetrieveFrame(highgui.CvCapture capture);
	/**
	 * Just a combination of cvGrabFrame and cvRetrieveFrame<br>
	 * !!!DO NOT RELEASE or MODIFY the retrieved frame!!!<br>
	 * Original signature : <code>IplImage* cvQueryFrame(CvCapture*)</code><br>
	 * <i>native declaration : otherlibs\highgui\highgui.h:256</i>
	 */
	cxcore.IplImage cvQueryFrame(highgui.CvCapture capture);
	/**
	 * stop capturing/reading and free resources<br>
	 * Original signature : <code>void cvReleaseCapture(CvCapture**)</code><br>
	 * <i>native declaration : otherlibs\highgui\highgui.h:259</i>
	 */
	void cvReleaseCapture(com.sun.jna.ptr.PointerByReference capture);
	/**
	 * retrieve or set capture properties<br>
	 * Original signature : <code>double cvGetCaptureProperty(CvCapture*, int)</code><br>
	 * <i>native declaration : otherlibs\highgui\highgui.h:280</i>
	 */
	double cvGetCaptureProperty(highgui.CvCapture capture, int property_id);
	/**
	 * Original signature : <code>int cvSetCaptureProperty(CvCapture*, int, double)</code><br>
	 * <i>native declaration : otherlibs\highgui\highgui.h:281</i>
	 */
	int cvSetCaptureProperty(highgui.CvCapture capture, int property_id, double value);
	/**
	 * initialize video file writer<br>
	 * Original signature : <code>CvVideoWriter* cvCreateVideoWriter(const char*, int, double, CvSize, int)</code><br>
	 * <i>native declaration : otherlibs\highgui\highgui.h:293</i><br>
	 * @deprecated use the safer method {@link #cvCreateVideoWriter(java.lang.String, int, double, cxcore.CvSize.ByValue, int)} instead
	 */
	@java.lang.Deprecated
	highgui.CvVideoWriter cvCreateVideoWriter(com.sun.jna.ptr.ByteByReference filename, int fourcc, double fps, cxcore.CvSize.ByValue frame_size, int is_color);
	/**
	 * initialize video file writer<br>
	 * Original signature : <code>CvVideoWriter* cvCreateVideoWriter(const char*, int, double, CvSize, int)</code><br>
	 * <i>native declaration : otherlibs\highgui\highgui.h:293</i>
	 */
	highgui.CvVideoWriter cvCreateVideoWriter(java.lang.String filename, int fourcc, double fps, cxcore.CvSize.ByValue frame_size, int is_color);
	/**
	 * write frame to video file<br>
	 * Original signature : <code>int cvWriteFrame(CvVideoWriter*, const IplImage*)</code><br>
	 * <i>native declaration : otherlibs\highgui\highgui.h:301</i>
	 */
	int cvWriteFrame(highgui.CvVideoWriter writer, cxcore.IplImage image);
	/**
	 * close video file writer<br>
	 * Original signature : <code>void cvReleaseVideoWriter(CvVideoWriter**)</code><br>
	 * <i>native declaration : otherlibs\highgui\highgui.h:304</i>
	 */
	void cvReleaseVideoWriter(com.sun.jna.ptr.PointerByReference writer);
	/**
	 * Original signature : <code>virtual bool ReadHeader()</code><br>
	 * <i>native declaration : otherlibs\highgui\grfmt_base.h:65</i>
	 */
	@com.ochafik.lang.jnaerator.runtime.Mangling({"_ZN11GrFmtReader10ReadHeaderEv", "?ReadHeader@GrFmtReader@@QAE_NXZ"})
	boolean GrFmtReader_ReadHeader();
	/**
	 * Original signature : <code>virtual bool ReadData(uchar*, int, int)</code><br>
	 * <i>native declaration : otherlibs\highgui\grfmt_base.h:66</i><br>
	 * @deprecated use the safer method {@link #GrFmtReader_ReadData(java.nio.ByteBuffer, int, int)} instead
	 */
	@com.ochafik.lang.jnaerator.runtime.Mangling({"_ZN11GrFmtReader8ReadDataEPhii", "?ReadData@GrFmtReader@@QAE_NPAEHH@Z"})
	@java.lang.Deprecated
	boolean GrFmtReader_ReadData(com.sun.jna.ptr.ByteByReference data, int step, int color);
	/**
	 * Original signature : <code>virtual bool ReadData(uchar*, int, int)</code><br>
	 * <i>native declaration : otherlibs\highgui\grfmt_base.h:66</i>
	 */
	@com.ochafik.lang.jnaerator.runtime.Mangling({"_ZN11GrFmtReader8ReadDataEPhii", "?ReadData@GrFmtReader@@QAE_NPAEHH@Z"})
	boolean GrFmtReader_ReadData(java.nio.ByteBuffer data, int step, int color);
	/**
	 * Original signature : <code>virtual bool WriteImage(const uchar*, int, int, int, int, int)</code><br>
	 * <i>native declaration : otherlibs\highgui\grfmt_base.h:89</i><br>
	 * @deprecated use the safer method {@link #GrFmtWriter_WriteImage(java.nio.ByteBuffer, int, int, int, int, int)} instead
	 */
	@com.ochafik.lang.jnaerator.runtime.Mangling({"_ZN11GrFmtWriter10WriteImageEPKhiiiii", "?WriteImage@GrFmtWriter@@QAE_NPAEHHHHH@Z"})
	@java.lang.Deprecated
	boolean GrFmtWriter_WriteImage(com.sun.jna.ptr.ByteByReference data, int step, int width, int height, int depth, int channels);
	/**
	 * Original signature : <code>virtual bool WriteImage(const uchar*, int, int, int, int, int)</code><br>
	 * <i>native declaration : otherlibs\highgui\grfmt_base.h:89</i>
	 */
	@com.ochafik.lang.jnaerator.runtime.Mangling({"_ZN11GrFmtWriter10WriteImageEPKhiiiii", "?WriteImage@GrFmtWriter@@QAE_NPAEHHHHH@Z"})
	boolean GrFmtWriter_WriteImage(java.nio.ByteBuffer data, int step, int width, int height, int depth, int channels);
	/**
	 * Original signature : <code>virtual GrFmtReader* NewReader(const char*)</code><br>
	 * <i>native declaration : otherlibs\highgui\grfmt_base.h:109</i><br>
	 * @deprecated use the safer method {@link #GrFmtFilterFactory_NewReader(java.lang.String)} instead
	 */
	@com.ochafik.lang.jnaerator.runtime.Mangling({"_ZN18GrFmtFilterFactory9NewReaderEPKc", "?NewReader@GrFmtFilterFactory@@QAEPA11GrFmtReaderPAD@Z"})
	@java.lang.Deprecated
	highgui.HighguiLibrary.GrFmtReader GrFmtFilterFactory_NewReader(com.sun.jna.ptr.ByteByReference filename);
	/**
	 * Original signature : <code>virtual GrFmtReader* NewReader(const char*)</code><br>
	 * <i>native declaration : otherlibs\highgui\grfmt_base.h:109</i>
	 */
	@com.ochafik.lang.jnaerator.runtime.Mangling({"_ZN18GrFmtFilterFactory9NewReaderEPKc", "?NewReader@GrFmtFilterFactory@@QAEPA11GrFmtReaderPAD@Z"})
	highgui.HighguiLibrary.GrFmtReader GrFmtFilterFactory_NewReader(java.lang.String filename);
	/**
	 * Original signature : <code>virtual GrFmtWriter* NewWriter(const char*)</code><br>
	 * <i>native declaration : otherlibs\highgui\grfmt_base.h:110</i><br>
	 * @deprecated use the safer method {@link #GrFmtFilterFactory_NewWriter(java.lang.String)} instead
	 */
	@com.ochafik.lang.jnaerator.runtime.Mangling({"_ZN18GrFmtFilterFactory9NewWriterEPKc", "?NewWriter@GrFmtFilterFactory@@QAEPA11GrFmtWriterPAD@Z"})
	@java.lang.Deprecated
	highgui.HighguiLibrary.GrFmtWriter GrFmtFilterFactory_NewWriter(com.sun.jna.ptr.ByteByReference filename);
	/**
	 * Original signature : <code>virtual GrFmtWriter* NewWriter(const char*)</code><br>
	 * <i>native declaration : otherlibs\highgui\grfmt_base.h:110</i>
	 */
	@com.ochafik.lang.jnaerator.runtime.Mangling({"_ZN18GrFmtFilterFactory9NewWriterEPKc", "?NewWriter@GrFmtFilterFactory@@QAEPA11GrFmtWriterPAD@Z"})
	highgui.HighguiLibrary.GrFmtWriter GrFmtFilterFactory_NewWriter(java.lang.String filename);
	/**
	 * <i>native declaration : otherlibs\highgui\gstappsink.h:47</i><br>
	 * Conversion Error : GType
	 */
	/**
	 * Original signature : <code>GST_DEBUG_CATEGORY_EXTERN()</code><br>
	 * <i>native declaration : otherlibs\highgui\gstappsink.h:49</i>
	 */
	@com.ochafik.lang.jnaerator.runtime.Mangling({"_Z25GST_DEBUG_CATEGORY_EXTERNv", "?GST_DEBUG_CATEGORY_EXTERN@@YAXXZ"})
	int GST_DEBUG_CATEGORY_EXTERN();
	/**
	 * Original signature : <code>void gst_app_sink_set_caps(GstAppSink*, const GstCaps*)</code><br>
	 * <i>native declaration : otherlibs\highgui\gstappsink.h:51</i>
	 */
	@com.ochafik.lang.jnaerator.runtime.Mangling({"_Z21gst_app_sink_set_capsP11_GstAppSinkPK7GstCaps", "?gst_app_sink_set_caps@@YAXPA11_GstAppSinkPA7GstCaps@Z"})
	void gst_app_sink_set_caps(highgui._GstAppSink appsink, highgui.HighguiLibrary.GstCaps caps);
	/**
	 * Original signature : <code>GstCaps* gst_app_sink_get_caps(GstAppSink*)</code><br>
	 * <i>native declaration : otherlibs\highgui\gstappsink.h:52</i>
	 */
	@com.ochafik.lang.jnaerator.runtime.Mangling({"_Z21gst_app_sink_get_capsP11_GstAppSink", "?gst_app_sink_get_caps@@YAPA7GstCapsPA11_GstAppSink@Z"})
	highgui.HighguiLibrary.GstCaps gst_app_sink_get_caps(highgui._GstAppSink appsink);
	/**
	 * <i>native declaration : otherlibs\highgui\gstappsink.h:54</i><br>
	 * Conversion Error : gboolean
	 */
	/**
	 * Original signature : <code>GstBuffer* gst_app_sink_pull_preroll(GstAppSink*)</code><br>
	 * <i>native declaration : otherlibs\highgui\gstappsink.h:56</i>
	 */
	@com.ochafik.lang.jnaerator.runtime.Mangling({"_Z25gst_app_sink_pull_prerollP11_GstAppSink", "?gst_app_sink_pull_preroll@@YAPA9GstBufferPA11_GstAppSink@Z"})
	highgui.HighguiLibrary.GstBuffer gst_app_sink_pull_preroll(highgui._GstAppSink appsink);
	/**
	 * Original signature : <code>GstBuffer* gst_app_sink_pull_buffer(GstAppSink*)</code><br>
	 * <i>native declaration : otherlibs\highgui\gstappsink.h:57</i>
	 */
	@com.ochafik.lang.jnaerator.runtime.Mangling({"_Z24gst_app_sink_pull_bufferP11_GstAppSink", "?gst_app_sink_pull_buffer@@YAPA9GstBufferPA11_GstAppSink@Z"})
	highgui.HighguiLibrary.GstBuffer gst_app_sink_pull_buffer(highgui._GstAppSink appsink);
	/**
	 * Original signature : <code>GstBuffer* gst_app_sink_peek_buffer(GstAppSink*)</code><br>
	 * <i>native declaration : otherlibs\highgui\gstappsink.h:58</i>
	 */
	@com.ochafik.lang.jnaerator.runtime.Mangling({"_Z24gst_app_sink_peek_bufferP11_GstAppSink", "?gst_app_sink_peek_buffer@@YAPA9GstBufferPA11_GstAppSink@Z"})
	highgui.HighguiLibrary.GstBuffer gst_app_sink_peek_buffer(highgui._GstAppSink appsink);
	/**
	 * <i>native declaration : otherlibs\highgui\gstappsink.h:60</i><br>
	 * Conversion Error : guint
	 */
	/**
	 * Original signature : <code>int* bsCreateSourceHuffmanTable(const uchar*, int*, int, int)</code><br>
	 * <i>native declaration : otherlibs\highgui\bitstrm.h:256</i><br>
	 * @deprecated use the safer method {@link #bsCreateSourceHuffmanTable(java.nio.ByteBuffer, java.nio.IntBuffer, int, int)} instead
	 */
	@com.ochafik.lang.jnaerator.runtime.Mangling({"_Z26bsCreateSourceHuffmanTablePKhPiii", "?bsCreateSourceHuffmanTable@@YAPAHPAEPAHHH@Z"})
	@java.lang.Deprecated
	com.sun.jna.ptr.IntByReference bsCreateSourceHuffmanTable(com.sun.jna.ptr.ByteByReference src, com.sun.jna.ptr.IntByReference dst, int max_bits, int first_bits);
	/**
	 * Original signature : <code>int* bsCreateSourceHuffmanTable(const uchar*, int*, int, int)</code><br>
	 * <i>native declaration : otherlibs\highgui\bitstrm.h:256</i>
	 */
	@com.ochafik.lang.jnaerator.runtime.Mangling({"_Z26bsCreateSourceHuffmanTablePKhPiii", "?bsCreateSourceHuffmanTable@@YAPAHPAEPAHHH@Z"})
	com.sun.jna.ptr.IntByReference bsCreateSourceHuffmanTable(java.nio.ByteBuffer src, java.nio.IntBuffer dst, int max_bits, int first_bits);
	/**
	 * Original signature : <code>bool bsCreateDecodeHuffmanTable(const int*, short*, int)</code><br>
	 * <i>native declaration : otherlibs\highgui\bitstrm.h:258</i><br>
	 * @deprecated use the safer methods {@link #bsCreateDecodeHuffmanTable(int[], java.nio.ShortBuffer, int)} and {@link #bsCreateDecodeHuffmanTable(java.nio.IntBuffer, java.nio.ShortBuffer, int)} instead
	 */
	@com.ochafik.lang.jnaerator.runtime.Mangling({"_Z26bsCreateDecodeHuffmanTablePKiPii", "?bsCreateDecodeHuffmanTable@@YA_NPAHPAHH@Z"})
	@java.lang.Deprecated
	boolean bsCreateDecodeHuffmanTable(com.sun.jna.ptr.IntByReference src, com.sun.jna.ptr.ShortByReference dst, int max_size);
	/**
	 * Original signature : <code>bool bsCreateDecodeHuffmanTable(const int*, short*, int)</code><br>
	 * <i>native declaration : otherlibs\highgui\bitstrm.h:258</i>
	 */
	@com.ochafik.lang.jnaerator.runtime.Mangling({"_Z26bsCreateDecodeHuffmanTablePKiPii", "?bsCreateDecodeHuffmanTable@@YA_NPAHPAHH@Z"})
	boolean bsCreateDecodeHuffmanTable(int src[], java.nio.ShortBuffer dst, int max_size);
	/**
	 * Original signature : <code>bool bsCreateDecodeHuffmanTable(const int*, short*, int)</code><br>
	 * <i>native declaration : otherlibs\highgui\bitstrm.h:258</i>
	 */
	@com.ochafik.lang.jnaerator.runtime.Mangling({"_Z26bsCreateDecodeHuffmanTablePKiPii", "?bsCreateDecodeHuffmanTable@@YA_NPAHPAHH@Z"})
	boolean bsCreateDecodeHuffmanTable(java.nio.IntBuffer src, java.nio.ShortBuffer dst, int max_size);
	/**
	 * Original signature : <code>bool bsCreateEncodeHuffmanTable(const int*, ulong*, int)</code><br>
	 * <i>native declaration : otherlibs\highgui\bitstrm.h:259</i><br>
	 * @deprecated use the safer methods {@link #bsCreateEncodeHuffmanTable(int[], com.sun.jna.ptr.NativeLongByReference, int)} and {@link #bsCreateEncodeHuffmanTable(java.nio.IntBuffer, com.sun.jna.ptr.NativeLongByReference, int)} instead
	 */
	@com.ochafik.lang.jnaerator.runtime.Mangling({"_Z26bsCreateEncodeHuffmanTablePKiPmi", "?bsCreateEncodeHuffmanTable@@YA_NPAHPAKH@Z"})
	@java.lang.Deprecated
	boolean bsCreateEncodeHuffmanTable(com.sun.jna.ptr.IntByReference src, com.sun.jna.ptr.NativeLongByReference dst, int max_size);
	/**
	 * Original signature : <code>bool bsCreateEncodeHuffmanTable(const int*, ulong*, int)</code><br>
	 * <i>native declaration : otherlibs\highgui\bitstrm.h:259</i>
	 */
	@com.ochafik.lang.jnaerator.runtime.Mangling({"_Z26bsCreateEncodeHuffmanTablePKiPmi", "?bsCreateEncodeHuffmanTable@@YA_NPAHPAKH@Z"})
	boolean bsCreateEncodeHuffmanTable(int src[], com.sun.jna.ptr.NativeLongByReference dst, int max_size);
	/**
	 * Original signature : <code>bool bsCreateEncodeHuffmanTable(const int*, ulong*, int)</code><br>
	 * <i>native declaration : otherlibs\highgui\bitstrm.h:259</i>
	 */
	@com.ochafik.lang.jnaerator.runtime.Mangling({"_Z26bsCreateEncodeHuffmanTablePKiPmi", "?bsCreateEncodeHuffmanTable@@YA_NPAHPAKH@Z"})
	boolean bsCreateEncodeHuffmanTable(java.nio.IntBuffer src, com.sun.jna.ptr.NativeLongByReference dst, int max_size);
	/**
	 * Original signature : <code>void bsBSwapBlock(uchar*, uchar*)</code><br>
	 * <i>native declaration : otherlibs\highgui\bitstrm.h:261</i><br>
	 * @deprecated use the safer method {@link #bsBSwapBlock(java.nio.ByteBuffer, java.nio.ByteBuffer)} instead
	 */
	@com.ochafik.lang.jnaerator.runtime.Mangling({"_Z12bsBSwapBlockPhPh", "?bsBSwapBlock@@YAXPAEPAE@Z"})
	@java.lang.Deprecated
	void bsBSwapBlock(com.sun.jna.ptr.ByteByReference start, com.sun.jna.ptr.ByteByReference end);
	/**
	 * Original signature : <code>void bsBSwapBlock(uchar*, uchar*)</code><br>
	 * <i>native declaration : otherlibs\highgui\bitstrm.h:261</i>
	 */
	@com.ochafik.lang.jnaerator.runtime.Mangling({"_Z12bsBSwapBlockPhPh", "?bsBSwapBlock@@YAXPAEPAE@Z"})
	void bsBSwapBlock(java.nio.ByteBuffer start, java.nio.ByteBuffer end);
	/**
	 * Original signature : <code>bool bsIsBigEndian()</code><br>
	 * <i>native declaration : otherlibs\highgui\bitstrm.h:262</i>
	 */
	@com.ochafik.lang.jnaerator.runtime.Mangling({"_Z13bsIsBigEndianv", "?bsIsBigEndian@@YA_NXZ"})
	boolean bsIsBigEndian();
	public static final class bs_bit_mask {
		private static com.sun.jna.Pointer bs_bit_mask;
		public static synchronized com.sun.jna.Pointer get() {
			if (bs_bit_mask == null) 
				bs_bit_mask = ((com.sun.jna.NativeLibrary)opencv.OpenCV.highgui).getGlobalVariableAddress("bs_bit_mask");
			return bs_bit_mask;
		}
	}
	/// Pointer to unknown (opaque) type
	public static class CvArr extends com.sun.jna.PointerType {
		public CvArr(com.sun.jna.Pointer pointer) {
			super(pointer);
		}
		public CvArr() {
			super();
		}
	}
	/// Pointer to unknown (opaque) type
	public static class GMutex extends com.sun.jna.PointerType {
		public GMutex(com.sun.jna.Pointer pointer) {
			super(pointer);
		}
		public GMutex() {
			super();
		}
	}
	/// Pointer to unknown (opaque) type
	public static class GQueue extends com.sun.jna.PointerType {
		public GQueue(com.sun.jna.Pointer pointer) {
			super(pointer);
		}
		public GQueue() {
			super();
		}
	}
	/// Pointer to unknown (opaque) type
	public static class GrFmtReader extends com.sun.jna.PointerType {
		public GrFmtReader(com.sun.jna.Pointer pointer) {
			super(pointer);
		}
		public GrFmtReader() {
			super();
		}
	}
	/// Pointer to unknown (opaque) type
	public static class GstBuffer extends com.sun.jna.PointerType {
		public GstBuffer(com.sun.jna.Pointer pointer) {
			super(pointer);
		}
		public GstBuffer() {
			super();
		}
	}
	/// Pointer to unknown (opaque) type
	public static class GrFmtWriter extends com.sun.jna.PointerType {
		public GrFmtWriter(com.sun.jna.Pointer pointer) {
			super(pointer);
		}
		public GrFmtWriter() {
			super();
		}
	}
	/// Pointer to unknown (opaque) type
	public static class GstCaps extends com.sun.jna.PointerType {
		public GstCaps(com.sun.jna.Pointer pointer) {
			super(pointer);
		}
		public GstCaps() {
			super();
		}
	}
	/// Pointer to unknown (opaque) type
	public static class GCond extends com.sun.jna.PointerType {
		public GCond(com.sun.jna.Pointer pointer) {
			super(pointer);
		}
		public GCond() {
			super();
		}
	}
}
