package highgui;
/**
 * <i>native declaration : otherlibs\highgui\\utils.h:45</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.free.fr/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a>, <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class PaletteEntry extends com.ochafik.lang.jnaerator.runtime.Structure {
	public byte b;
	public byte g;
	public byte r;
	public byte a;
	public PaletteEntry() {
		super();
	}
	public PaletteEntry(byte b, byte g, byte r, byte a) {
		super();
		this.b = b;
		this.g = g;
		this.r = r;
		this.a = a;
	}
	public ByReference byReference() { return setupClone(new ByReference()); }
	public ByValue byValue() { return setupClone(new ByValue()); }
	public PaletteEntry clone() { return setupClone(new PaletteEntry()); }
	public static class ByReference extends PaletteEntry implements com.sun.jna.Structure.ByReference {}
	public static class ByValue extends PaletteEntry implements com.sun.jna.Structure.ByValue {}
}
